### ISSUE TITLE
Using actix-web without default-features breaks awc

### ISSUE THREAD

**Issue by igor-raits** [actix/actix-web#1215]
Hello,

I'm trying to port https://github.com/getzola/zola to the latest actix-web dependencies.

```toml
actix-files = "0.2.0-alpha.3"                                                                                 
actix-web = { version = "2.0.0-alpha.5", default-features = false, features = [] }                            
```

With this dependencies, I get following error:

```rust
error[E0432]: unresolved import `actix_http::encoding`
  --> /home/brain/.cargo/registry/src/github.com-1ecc6299db9ec823/awc-1.0.0/src/sender.rs:15:17
   |
15 | use actix_http::encoding::Decoder;
   |                 ^^^^^^^^ could not find `encoding` in `actix_http`
```

which implies that awc depends on actix_http with feature `compress` unconditionally, so that disabling default deps on actix-web breaks enablement of that one.

I am not sure what would be the proper fix apart from not using default-features, so opening this ticket.

Thanks in advance!

**Comment by igor-raits** [comment]
Probably changing https://github.com/actix/actix-web/blob/e8e0f98f96c1ae09fd2c2cf32f4c47a443e5e852/Cargo.toml#L75 to depend on `compress` feautre would be enough...

**Comment by igor-raits** [comment]
Or other way around, setting `default-features = false` for `awc` and `actix-http` dependencies would solve it.

**Comment by eclipseo** [comment]
Building actix-files-0.2.0~alpha.3 triggers the same issue:

```
Compiling awc v1.0.0
     Running `/usr/bin/rustc --edition=2018 --crate-name awc /usr/share/cargo/registry/awc-1.0.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C metadata=1077ace2f09ee613 -C extra-filename=-1077ace2f09ee613 --out-dir /builddir/build/BUILD/actix-files-0.2.0-alpha.3/target/release/deps -L dependency=/builddir/build/BUILD/actix-files-0.2.0-alpha.3/target/release/deps --extern actix_codec=/builddir/build/BUILD/actix-files-0.2.0-alpha.3/target/release/deps/libactix_codec-c86050f4bd5453ea.rmeta --extern actix_http=/builddir/build/BUILD/actix-files-0.2.0-alpha.3/target/release/deps/libactix_http-d2dede41b2fa66ce.rmeta --extern actix_rt=/builddir/build/BUILD/actix-files-0.2.0-alpha.3/target/release/deps/libactix_rt-29c8823e5ddbaba8.rmeta --extern actix_service=/builddir/build/BUILD/actix-files-0.2.0-alpha.3/target/release/deps/libactix_service-bdd9562474c79818.rmeta --extern base64=/builddir/build/BUILD/actix-files-0.2.0-alpha.3/target/release/deps/libbase64-a829e8f0f8a93cfb.rmeta --extern bytes=/builddir/build/BUILD/actix-files-0.2.0-alpha.3/target/release/deps/libbytes-976b9e97924d7477.rmeta --extern derive_more=/builddir/build/BUILD/actix-files-0.2.0-alpha.3/target/release/deps/libderive_more-fb27ff044dc34354.so --extern futures_core=/builddir/build/BUILD/actix-files-0.2.0-alpha.3/target/release/deps/libfutures_core-7125d5dc71f40bb7.rmeta --extern log=/builddir/build/BUILD/actix-files-0.2.0-alpha.3/target/release/deps/liblog-3adf555e00718733.rmeta --extern mime=/builddir/build/BUILD/actix-files-0.2.0-alpha.3/target/release/deps/libmime-382f0e7a522eb649.rmeta --extern percent_encoding=/builddir/build/BUILD/actix-files-0.2.0-alpha.3/target/release/deps/libpercent_encoding-dd130180f034cb7e.rmeta --extern rand=/builddir/build/BUILD/actix-files-0.2.0-alpha.3/target/release/deps/librand-573ef42a091e8257.rmeta --extern serde=/builddir/build/BUILD/actix-files-0.2.0-alpha.3/target/release/deps/libserde-5927969e814d112d.rmeta --extern serde_json=/builddir/build/BUILD/actix-files-0.2.0-alpha.3/target/release/deps/libserde_json-9c0db8bc616fb1f6.rmeta --extern serde_urlencoded=/builddir/build/BUILD/actix-files-0.2.0-alpha.3/target/release/deps/libserde_urlencoded-eb3621dd91a6b28e.rmeta --cap-lints allow -Copt-level=3 -Cdebuginfo=2 -Clink-arg=-Wl,-z,relro,-z,now -Ccodegen-units=1 --cap-lints=warn -L native=/builddir/build/BUILD/actix-files-0.2.0-alpha.3/target/release/build/backtrace-sys-b885eba3e914adc3/out`
error[E0432]: unresolved import `actix_http::encoding`
  --> /usr/share/cargo/registry/awc-1.0.0/src/sender.rs:15:17
   |
15 | use actix_http::encoding::Decoder;
   |                 ^^^^^^^^ could not find `encoding` in `actix_http`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0432`.
error: could not compile `awc`.
```

actix-web is set to default-features = false there too:

```
[dependencies.actix-web]
version = "2.0.0-alpha.3"
default-features = false
```

**Comment by igor-raits** [comment]
So this is apparently caused by `-Zavoid-dev-deps`. But this is not really broken because it simply ignores dev-dependencies.

When you have actix-web with no-default-features in dependencies and then you have it in dev-dependencies with default-features, then without -Zavoid-dev-deps, you get basically default features enabled everywhere. And that applies only to top-level component. That's why @eclipseo gets this error for actix-files.

But it is broken for everyone who wants to use actix-web without default features.

**Comment by fafhrd91** [comment]
awc 1.0.1 is released, but you still need actix-web from master

**Comment by igor-raits** [comment]
@fafhrd91 would it be possible to release new actix-web as well?

**Comment by fafhrd91** [comment]
later

**Comment by ph1ex0n** [comment]
problem not resolved

``error[E0432]: unresolved import `actix_http::error::BlockingError`
 --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.20/src/error/mod.rs:9:5
  |
9 |     BlockingError, ContentTypeError, DispatchError, HttpError, ParseError, PayloadError,
  |     ^^^^^^^^^^^^^ no `BlockingError` in `error`

error[E0412]: cannot find type `BlockingError` in module `actix_http::error`
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.20/src/error/response_error.rs:110:43
    |
110 | impl ResponseError for actix_http::error::BlockingError {}
    |                                           ^^^^^^^^^^^^^ not found in `actix_http::error`

error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.20/src/app_service.rs:285:52
    |
285 |                     router.rdef(path, service).2 = guards;
    |                     ----------------------------   ^^^^^^ expected `&mut _`, found enum `std::option::Option`
    |                     |
    |                     expected due to the type of this binding
    |
    = note: expected mutable reference `&mut _`
                            found enum `std::option::Option<Vec<Box<dyn Guard>>>`
help: consider dereferencing here to assign to the mutable borrowed piece of memory
    |
285 |                     *router.rdef(path, service).2 = guards;
    |                     +

error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.20/src/app_service.rs:310:20
    |
310 |             if let Some(ref guards) = guards {
    |                    ^^^^^^^^^^^^^^^^   ------ this expression has type `&Vec<Box<dyn Guard>>`
    |                    |
    |                    expected struct `Vec`, found enum `std::option::Option`
    |
    = note: expected struct `Vec<Box<dyn Guard>>`
                 found enum `std::option::Option<_>`

error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.20/src/scope.rs:487:52
    |
487 |                     router.rdef(path, service).2 = guards;
    |                     ----------------------------   ^^^^^^ expected `&mut _`, found enum `std::option::Option`
    |                     |
    |                     expected due to the type of this binding
    |
    = note: expected mutable reference `&mut _`
                            found enum `std::option::Option<Vec<Box<dyn Guard>>>`
help: consider dereferencing here to assign to the mutable borrowed piece of memory
    |
487 |                     *router.rdef(path, service).2 = guards;
    |                     +

error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.20/src/scope.rs:511:20
    |
511 |             if let Some(ref guards) = guards {
    |                    ^^^^^^^^^^^^^^^^   ------ this expression has type `&Vec<Box<dyn Guard>>`
    |                    |
    |                    expected struct `Vec`, found enum `std::option::Option`
    |
    = note: expected struct `Vec<Box<dyn Guard>>`
                 found enum `std::option::Option<_>`

error[E0308]: mismatched types
  --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.20/src/server.rs:91:48
   |
91 |                 keep_alive: KeepAlive::Timeout(5),
   |                                                ^ expected struct `std::time::Duration`, found integer

error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.20/src/server.rs:294:41
    |
294 |                         .client_timeout(c.client_timeout)
    |                                         ^^^^^^^^^^^^^^^^ expected struct `std::time::Duration`, found `u64`

error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.20/src/server.rs:295:44
    |
295 |                         .client_disconnect(c.client_shutdown)
    |                                            ^^^^^^^^^^^^^^^^^ expected struct `std::time::Duration`, found `u64`

error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.20/src/server.rs:540:37
    |
540 |                     .client_timeout(c.client_timeout)
    |                                     ^^^^^^^^^^^^^^^^ expected struct `std::time::Duration`, found `u64`

error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.20/src/server.rs:541:40
    |
541 |                     .client_disconnect(c.client_shutdown);
    |                                        ^^^^^^^^^^^^^^^^^ expected struct `std::time::Duration`, found `u64`

   Compiling awc v3.0.0
error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.20/src/server.rs:596:41
    |
596 |                         .client_timeout(c.client_timeout)
    |                                         ^^^^^^^^^^^^^^^^ expected struct `std::time::Duration`, found `u64`

error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.20/src/server.rs:597:44
    |
597 |                         .client_disconnect(c.client_shutdown)
    |                                            ^^^^^^^^^^^^^^^^^ expected struct `std::time::Duration`, found `u64`

Some errors have detailed explanations: E0308, E0412, E0432.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `actix-web` due to 13 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
`

**Comment by robjtede** [comment]
@ph1ex0n check out the [migration guide](https://github.com/actix/actix-web/blob/master/actix-web/MIGRATION-4.0.md) and [v4 API docs](docs.rs/actix-web/4) to help solve your issues.

**Comment by ph1ex0n** [comment]
thx
> @ph1ex0n check out the [migration guide](https://github.com/actix/actix-web/blob/master/actix-web/MIGRATION-4.0.md) and [v4 API docs](docs.rs/actix-web/4) to help solve your issues.
