### ISSUE TITLE
actix-files: set_content_encoding does not work for NamedFile

### ISSUE THREAD

**Issue by vmalloc** [actix/actix-web#1242]
I'm trying to force a content-encoding on a served file (using actix-files).

Trying this code in actix-files 1.0.7, actix-web 1.0.9:
```rust
use actix_files::NamedFile;
use actix_web::{web, App, HttpServer, Responder};

fn serve() -> impl Responder {
    NamedFile::open("/tmp/testfile")
        .unwrap()
        .set_content_encoding(actix_web::http::header::ContentEncoding::Gzip)
}

fn main() {
    HttpServer::new(|| App::new().route("/serve", web::get().to(serve)))
        .bind("127.0.0.1:8000")
        .expect("Can not bind to port 8000")
        .run()
        .unwrap();
}
```
It seems that the file is served without the requested content encoding:
```
$ curl -vvv http://127.0.0.1:8000/serve
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> GET /serve HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< content-length: 6
< content-type: text/plain
< content-disposition: inline; filename="testfile"
< last-modified: Sun, 29 Dec 2019 10:20:24 GMT
< etag: "1cf1aac:6:5e087de8:8203cc6"
< accept-ranges: bytes
< date: Sun, 29 Dec 2019 10:27:03 GMT
<
hello
* Connection #0 to host 127.0.0.1 left intact
* Closing connection 0
```

**Comment by vmalloc** [comment]
Temporarily workard around this by doing:
```rust
    let mut resp = NamedFile::open("/tmp/testfile")
        .unwrap()
        .respond_to(&req)
        .unwrap();

    let resp = HttpResponse::Ok()
        .set_header("Content-encoding", "gzip")
        .streaming(resp.take_body());
    resp

```
Not too happy about it, but it works...

**Comment by fafhrd91** [comment]
Could be a bug

**Comment by Gowee** [comment]
On the master version actix-web 3.2.0 / actix-files 0.4.0, I cannot reproduce the problem. `send_content_encoding` works as intended.

@vmalloc Is the following the expected?

```
$ echo "hello" > /tmp/testfile
$ curl -vvvv http://127.0.0.1:8080 --output -   
*   Trying 127.0.0.1:8080...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.73.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< transfer-encoding: chunked
< x-version: 0.2
< last-modified: Sat, 31 Oct 2020 09:59:11 GMT
< accept-ranges: bytes
< content-encoding: gzip
< content-type: application/octet-stream
< etag: "ab4:6:5f9d356f:d779233"
< content-disposition: attachment; filename="testfile"
< date: Sat, 31 Oct 2020 09:59:17 GMT
< 
* Connection #0 to host 127.0.0.1 left intact
��H���� 0:6⏎               
```
I misunderstood the issue just now, so please ignore the stricken-through text below. 

---
<del>It appears to be the intended behaviour.</del>
https://github.com/actix/actix-web/blob/26c1a901d9bef752a1f6afe3af6adcba1ca78ce7/actix-files/src/named.rs#L215
https://github.com/actix/actix-web/blob/26c1a901d9bef752a1f6afe3af6adcba1ca78ce7/actix-files/src/named.rs#L378
<del>That is, `set_content_encoding` set the encoding into which actix-web encodes the `NamedFile`, instead of just setting the HTTP header `Content-Encoding`. </del>
<del>It looks somewhat counter-intuitive. Would it be better to rename the method to be something like `encode_content`, `encoded_with`, etc.? Besides, I suppose a new method is required to support to add a custom header.</del>

<del>Related commit: https://github.com/actix/actix-web/commit/e254fe4f9c37da954c4bf544ca30207415dbd426
</del>

**Comment by aliemjay** [comment]
`Compress` middleware must be active to do the actual compression. See https://actix.rs/docs/response/
