### ISSUE TITLE
`default_service` doesn't use guard

### ISSUE THREAD

**Issue by yim7** [actix/actix-web#1255]
I am learning the example https://actix.rs/docs/url-dispatch/#changing-the-default-not-found-response. My expected result is that not matched requets except `GET` method use default_service,  but it seems that guard does not work and all matched requests return 405.
The guard in default service will not be used?
# Example
``` rust
use actix_web::{dev::RequestHead, guard::Guard, web, App, HttpResponse, HttpServer};

struct FailGuard;

impl Guard for FailGuard {
    fn check(&self, req: &RequestHead) -> bool {
        false
    }
}

async fn index() -> HttpResponse {
    HttpResponse::Ok().body("Hello")
}

async fn default() -> HttpResponse {
    HttpResponse::Ok().body("Default")
}

#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new()
            .route("/resource/", web::get().guard(FailGuard).to(index))
            .default_service(web::route().guard(FailGuard).to(default))
    })
    .bind("127.0.0.1:8088")?
    .run()
    .await
}
```

**Comment by fafhrd91** [comment]
this is expected behavior, but PR is welcomed

**Comment by yim7** [comment]
Thanks. I read the code and understood that the default service doesn't check guards, but I can use resource to configure the default routes.

**Comment by ssokolow** [comment]
> but I can use resource to configure the default routes

Mind explaining this so people coming in off Google don't have to also go digging around in the code to understand how actix-web works?

(I was planning to use a guard to enforce security in a custom static file serving thing so this is a bit of a footgun.)

**Comment by robjtede** [comment]
Guards are only for influencing routing decisions; the fact that you hit the `default_service` means that none of the other registered routes on that App/Scope/Resource matched the request path.

Let's say you were able to place a guard on the `default_service`. Then there would need to be a `default_default_service` to handle requests that didn't pass those guards, etc, etc.

Guards are not a security mechanism, you should choose a middleware or extractor for that; either of those can respond with proper errors.

**Comment by ssokolow** [comment]
> Guards are not a security mechanism

I was very unclear but what I meant my point to be is that it's not obvious enough from the documentation.

Just looking at the docs, it's easy to conclude "If I want to do this without tying my code in knots, and I want it to be reusable, I should use a guard".

Intuitively, middleware is something that applies to *everything*... not just the route that hits the filesystem (eg. ERROR: Cannot load `/_/base.css` from rust-embed because someone created that path in the filesystem and the middleware applies before the router does), and doing something like crafting a "ShareableDirectoryPath" extractor and a "ShareableFilePath" extractor and letting the router try the second if the first fails isn't exactly an obvious idea. (And that *is* the first design that came to mind when you suggested an extractor.)

...and with the docs not having a big message that communicates "Don't do it this way!" or "Don't use it for this!", I actually found myself contemplating accepting the scalability hit and just using blocking filesystem calls in a guard.
