### ISSUE TITLE
How to handle application/json?

### ISSUE THREAD

**Issue by ghost** [actix/actix-web#13]
First of, let me say: thanks for your time and all the effort you put into actix-web!

Secondly, my question would be considering json post requests. How would you handle them? Could you give an example?

**Comment by fafhrd91** [comment]
Unfortunately, because of async nature of actix, it is not very ergonomic to deal with requests body.
you need to load body into memory and then deserialize it. I am planing to add some functionality, which should simplify body processing.

for now I added example https://github.com/actix/actix-web/blob/master/examples/json/src/main.rs
and guide section https://actix.github.io/actix-web/guide/qs_7.html#json-request

**Comment by fafhrd91** [comment]
re-open if you need anything else

**Comment by fafhrd91** [comment]
added json support https://actix.github.io/actix-web/actix_web/struct.HttpRequest.html#method.json
