### ISSUE TITLE
Port already in use does not cause error on Windows + WSL

### ISSUE THREAD

**Issue by wahur666** [actix/actix-web#1335]
## Expected Behavior
When you start up the HttpServer the bind("127.0.0.1:65000")? throws an error when the port referenced is under use.

## Current Behavior
You can start up as many instances of the same application as you want (tested up to 3) and none of the later started throw error on the fact that the port is already bound. In fact, the first instance catches the requests, the other ones does not receive it. When you terminate the first instance, the second will catch the requests. And if that is terminated then the third. And when the third is terminated, then the request fails as expected.

## Steps to Reproduce (for bugs)
1. Use the barebone application code, what can be found in the examples
2. Run multiple instances

## Context
This can cause a mayor issue if you bind your port on something you don't know is already been used, for example by a running SQL server.

## Your Environment
Windows 10, WSL - Ubuntu

* Rust Version: rustc 1.41.0 (5e1a79984 2020-01-27)
* Actix Web Version: 2.0, 1.0.8

**Comment by Rudi3** [comment]
That happens because the socket is opened with `SO_REUSEADDR`. Also see my comment to a socket issue also related to bind problems: https://github.com/actix/actix-web/issues/1249#issuecomment-581046322.

I'm not sure if `SO_REUSEADDR` is desireable altogether, since it won't cause an error when the port/address already is in use (and will still lead to the server not working).

**Comment by Rudi3** [comment]
I believe just using plain `TcpListener::bind` should fix that: https://github.com/actix/actix-web/compare/master...Rudi3:use_std_TcpListener. I don't want to make a PR just yet, as it's not cleaned up yet and I'm not sure if `SO_REUSEADDR` has a deeper meaning I'm not aware of.

**Comment by ccope** [comment]
I assume this is configured to allow seamless restarts during updates. Maybe in debug mode it should warn if there are multiple processes listening?

The behavior of this flag also varies by OS, so it should be cfg gated for consistent behavior. The more commonly used variant of this flag in Linux is SO_REUSEPORT. With that setting, the Linux kernel will actually do load balancing of connections between all of the processes which have opened the port (as long as they all use this flag and share the same UID).

More info on the behavior of the flag and the platform differences:
https://stackoverflow.com/a/14388707/1342791

**Comment by Rudi3** [comment]
@ccope thanks, that link is very comprehensive. But shouldn't we get an error then if `SO_REUSEADDR` is currently being used and it's bound to **exactly** the same address and port? 

But it's on windows, so that changes things:

> Windows only knows the SO_REUSEADDR option, there is no SO_REUSEPORT. Setting SO_REUSEADDR on a socket in Windows behaves like setting SO_REUSEPORT and SO_REUSEADDR on a socket in BSD, with one exception: A socket with SO_REUSEADDR can always bind to exactly the same source address and port as an already bound socket, even if the other socket did not have this option set when it was bound. This behavior is somewhat dangerous because it allows an application "to steal" the connected port of another application.

So if I got that right, `SO_REUSEADDR` only behaves like `SO_REUSEPORT` on Windows, which should mean that this would only work on windows and you should currently get an error on linux?

If that's right, it should definately at least have a cfg that is consistent, as you said.

**Comment by wahur666** [comment]
@Rudi3 @ccope I can verify that information, that on Ubuntu **it will raise exception** on bound port!

**Comment by RandomGHUser** [comment]
This issue still occurs on windows (probably until the PR above gets merged) - the workaround below should check the availability and panic if port is not available (untested)
```rust
fn assert_address() {
    if cfg!(target_os = "windows") {
        match std::net::TcpListener::bind("localhost:8080") {
            Ok(e) => e,
            Err(e) => {
                println!("Could not open port 8080 on localhost");
                panic!(e);
            }
        };
    }
}
```
