### ISSUE TITLE
actix-web/actix-files doesn't put a Content-Length on range responses

### ISSUE THREAD

**Issue by djahandarie** [actix/actix-web#1384]
It seems that if you do a range request to a [`Files`](https://docs.rs/actix-files/0.2.1/actix_files/struct.Files.html)-backed resource, you will get a `Content-Range` header back in the 206, but not a `Content-Length` back:

```
  HTTP/1.1 206 Partial Content
  transfer-encoding: chunked
  last-modified: Wed, 26 Feb 2020 18:01:01 GMT
  accept-ranges: bytes
  cache-control: max-age=100
  content-type: application/octet-stream
  content-range: bytes 0-100/3238690816
  etag: "8e6d2f:c10a8000:5e56b25d:207070e2"
  content-disposition: attachment; filename="data.db"
  date: Wed, 26 Feb 2020 23:40:44 GMT
```

While [RFC 7223: Hypertext Transfer Protocol (HTTP/1.1): Range Requests](https://tools.ietf.org/html/rfc7233) doesn't seem to explicitly forbid omitting a `Content-Length` header, all of the examples in it do include the `Content-Length` in 206 responses, e.g.:

```
     HTTP/1.1 206 Partial Content
     Date: Wed, 15 Nov 1995 06:25:24 GMT
     Last-Modified: Wed, 15 Nov 1995 04:58:08 GMT
     Content-Range: bytes 21010-47021/47022
     Content-Length: 26012
     Content-Type: image/gif

     ... 26012 bytes of partial image data ...
```
(From [section 4.1](https://tools.ietf.org/html/rfc7233#section-4.1))

In addition, a reverse proxy/CDN I'm using in front of my app also requires the Content-Length header, which is how I noticed this issue.

I *think* this is a regression in actix-web 2.

**Comment by omid** [comment]
It's related to #930

**Comment by robjtede** [comment]
The reason that a content length is not included in OP's response is that it's using `transfer-encoding: chunked` which adds in the content lengths preceeding each chunk instead of as a primary header.

Your PR as it stands @omid would cause all files served by actix-files to be sent as a single payload which would necessitate loading the whole file into memory. This could be problematic for very large files and likely why chunked encoding was chosen as the transfer method in the first place.

The posted HTTP response seems entirely valid. To me, it would be an oversight or a bug that a proxy/CDN does not support chunked transfers.

**Comment by fafhrd91** [comment]
actix-files does not use chunked encoding

**Comment by omid** [comment]
@robjtede AFAICS and also @fafhrd91 said actix-files doesn't use chunking. The problem was happening only in case of asking for a specific range of the file. But the whole file was always fine and without chunks.

Let me share with you some more insights. Please see the following commands and responses:

**Before my changes:**

Ask for the whole file:
```
curl -vvv 'http://0.0.0.0:8081/static/index.html' > /dev/null
> GET /static/index.html HTTP/1.1
> Host: 0.0.0.0:8081
> User-Agent: curl/7.70.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 2074
< last-modified: Sun, 03 May 2020 09:48:08 GMT
< accept-ranges: bytes
< content-type: text/html
< etag: "114457b:81a:5eae9358:73e1149"
< content-disposition: inline; filename="index.html"
< date: Sat, 09 May 2020 07:17:32 GMT
```

Ask for the first part of the file (It's important here, because of `offset != 0` condition in the code):
```
curl -r 0-20 -vvv 'http://0.0.0.0:8081/static/index.html' > /dev/null
> GET /static/index.html HTTP/1.1
> Host: 0.0.0.0:8081
> Range: bytes=0-20
> User-Agent: curl/7.70.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 206 Partial Content
< transfer-encoding: chunked
< last-modified: Sun, 03 May 2020 09:48:08 GMT
< accept-ranges: bytes
< content-type: text/html
< content-range: bytes 0-20/2074
< etag: "114457b:81a:5eae9358:73e1149"
< content-disposition: inline; filename="index.html"
< date: Sat, 09 May 2020 07:17:37 GMT
```

Ask for any other part of the file:
```
curl -r 10-20 -vvv 'http://0.0.0.0:8081/static/index.html' > /dev/null
> GET /static/index.html HTTP/1.1
> Host: 0.0.0.0:8081
> Range: bytes=10-20
> User-Agent: curl/7.70.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 206 Partial Content
< transfer-encoding: chunked
< last-modified: Sun, 03 May 2020 09:48:08 GMT
< accept-ranges: bytes
< content-type: text/html
< content-range: bytes 10-20/2074
< etag: "114457b:81a:5eae9358:73e1149"
< content-disposition: inline; filename="index.html"
< date: Sat, 09 May 2020 07:17:41 GMT
```

**After my changes:**

Ask for the whole file:
```
curl -vvv 'http://0.0.0.0:8081/static/index.html' > /dev/null
> GET /static/index.html HTTP/1.1
> Host: 0.0.0.0:8081
> User-Agent: curl/7.70.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 2074
< last-modified: Sun, 03 May 2020 09:48:08 GMT
< accept-ranges: bytes
< content-type: text/html
< etag: "114457b:81a:5eae9358:73e1149"
< content-disposition: inline; filename="index.html"
< date: Sat, 09 May 2020 07:03:34 GMT
```

Ask for the first part of the file (It's important here, because of `offset != 0` condition in the code):
```
curl -r 0-20 -vvv 'http://0.0.0.0:8081/static/index.html' > /dev/null
> GET /static/index.html HTTP/1.1
> Host: 0.0.0.0:8081
> Range: bytes=0-20
> User-Agent: curl/7.70.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 206 Partial Content
< content-length: 21
< last-modified: Sun, 03 May 2020 09:48:08 GMT
< accept-ranges: bytes
< content-type: text/html
< content-range: bytes 0-20/2074
< etag: "114457b:81a:5eae9358:73e1149"
< content-disposition: inline; filename="index.html"
< date: Sat, 09 May 2020 07:03:49 GMT
```

Ask for any other part of the file:
```
curl -r 10-20 -vvv 'http://0.0.0.0:8081/static/index.html' > /dev/null
> GET /static/index.html HTTP/1.1
> Host: 0.0.0.0:8081
> Range: bytes=10-20
> User-Agent: curl/7.70.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 206 Partial Content
< content-length: 11
< last-modified: Sun, 03 May 2020 09:48:08 GMT
< accept-ranges: bytes
< content-type: text/html
< content-range: bytes 10-20/2074
< etag: "114457b:81a:5eae9358:73e1149"
< content-disposition: inline; filename="index.html"
< date: Sat, 09 May 2020 07:04:00 GMT
```

And @fafhrd91, thanks, you are right... I shouldn't set no_chunking in actix_files, with SizedStream it automatically doesn't do chunking.
