### ISSUE TITLE
Why chrono is removed?

### ISSUE THREAD

**Issue by sergeysova** [actix/actix-web#1432]
#789

But CookieBuilder still using time, instead of chrono.

My case:
- I have `chrono::NaiveDateTime` from my business-logic layer, and I want to set cookie expiration time.

**Comment by sergeysova** [comment]
@JohnTitor What about to migrate to `chrono` in 3.0.0? I can help with it

**Comment by pfrenssen** [comment]
It is explained in the PR you linked why it is removed: https://github.com/actix/actix-web/pull/789#issuecomment-485041718

**Comment by sergeysova** [comment]
But chrono supports it. https://github.com/chronotope/chrono/issues/403#issuecomment-605666733

**Comment by pfrenssen** [comment]
I don't have an opinion on this, I didn't remove it, @fafhrd91 did. I'm just answering your question. You asked why it was removed, the answer to your question is in the comment I linked. We cannot ask for more details surrounding this unfortunately, since the original author is sadly no longer with us.

**Comment by 0x8f701** [comment]
can this be closed? @sergeysove

**Comment by sergeysova** [comment]
What about to add support for chrono?

**Comment by 0x8f701** [comment]
@sergeysova Could you make a PR to add it?
