### ISSUE TITLE
Can not compile with Bazel: use of undeclared type or module `fail_ure`

### ISSUE THREAD

**Issue by DmitryRusakovKodiak** [actix/actix-web#1443]
Hi, I'm trying to compile the following actix-web example in my Bazel project: https://github.com/actix/examples/tree/master/multipart
and I have ended up with the following error:

```
error[E0433]: failed to resolve: use of undeclared type or module `fail_ure`
   --> third_party/cargo/vendor/actix-http-1.0.1/src/error.rs:968:24
    |
968 | impl ResponseError for fail_ure::Error {}
    |                        ^^^^^^^^ use of undeclared type or module `fail_ure`

error: aborting due to previous error
```

I vendored all the dependencies from https://github.com/actix/examples/blob/master/multipart/Cargo.toml
by means of cargo-raze.

@JohnTitor I know you have already encountered this problem in the past. Any ideas how to fix it?

**Comment by JohnTitor** [comment]
I think there's no actionable item on our side as explained in the issue: https://github.com/actix/actix-web/issues/1318#issuecomment-584707321

But the failure crate will be deprecated in the near future, see [internal thread for the context](https://internals.rust-lang.org/t/failure-crate-maintenance/12087?u=johntitor).
So I'd like to remove the dependency and the feature rather than introduce an actual fix.

**Comment by DmitryRusakovKodiak** [comment]
@JohnTitor Does that mean that it is impossible to compile actix-web with Bazel until the failure crate is deprecated?

**Comment by JohnTitor** [comment]
@DmitryRusakovKodiak Or you can disable that feature if you don't need.

**Comment by dnrusakov** [comment]
@JohnTitor Ok, how to disable it?

**Comment by robjtede** [comment]
@dnrusakov failure is part of the default features, you'll have to disable them. In Cargo.toml this would be `default-features = false`.

**Comment by JohnTitor** [comment]
I'd like to close this issue in favor of Rob's comment.
Just fyi, I've submitted the PR to remove that dep and feature, though we still have renamed deps.
