### ISSUE TITLE
Unable to add route assigned to variable

### ISSUE THREAD

**Issue by unional** [actix/actix-web#1490]
This does not compile:
```rust
let route = web::get().to(greet);
HttpServer::new(|| {
  App::new().route("/", route)
});
```
while these can:
```rust
HttpServer::new(|| {
  App::new().route("/", web::get().to(greet))
});
```
```rust
HttpServer::new(|| {
  let route = web::get().to(greet);
  App::new().route("/", route)
});
```

Is this a language limitation?
It is weird that the closure does not seem to capture the variable in scope correctly.

## Expected Behavior
all can be compiled

## Actual Behavior
first one does not

rustc - 1.43.0
actix-web 2.0

**Comment by robjtede** [comment]
There are a few things contributing to this not being possible.

- `App.route` takes ownership of a `Route`.
- `HttpServer::new(...)` takes a `Fn() -> ...`
  - Since `App` is created multiple times (once for each worker).
  - This means that the closures passed in could be called multiple times so needs a guaranteed valid environment every time.
  - Therefore, the environment captured can only include references or Copy items.

Additionally, `Route` is not `Clone` so using a `move ||` closure and `route.clone()` will also not work.

I would not call this a language "limitation". It is quite definitely a feature of Rust, and there would be many more sad times without it.

Reading up on the relationship and differences of `Fn`, `FnMut` & `FnOnce` will help you to read the function definitions in the docuemntation better, then you can immediately know what's possible.

**Comment by unional** [comment]
Thanks!

> Since App is created multiple times (once for each worker).

This help a lot.

What I tried to do is a plugin system where routes are defined in the plugins.
So seems like the best thing I can do is load the plugins outside,
and initialize them inside the closure so that each worker will get their own copy of routes to work with.

**Comment by unional** [comment]
Just FYI, it seems like I couldn't "load the plugins outside" either because I can't do `move || {}` to move the `lib` into the macro (where `let lib = libloading::Library::new("some-plugin")`).
