### ISSUE TITLE
Replace `net2` dependency

### ISSUE THREAD

**Issue by vbrandl** [actix/actix-web#1516]
The `net2` crate has been deprecated. [RUSTSEC recommends](https://rustsec.org/advisories/RUSTSEC-2020-0016.html) moving away from `net2` and use [`socket2`](https://crates.io/crates/socket2) instead, following the recommendation of the `net2` authors.

Here is [the official deprecation notice](https://github.com/deprecrated/net2-rs#net2-is-deprecated).

Users of [`cargo-audit`](https://github.com/RustSec/cargo-audit) or the [`actions-rs/audit-check`](https://github.com/actions-rs/audit-check) Action should get notifications about the deprecation: https://github.com/vbrandl/hoc/issues/143.

**Comment by rodya-mirov** [comment]
Has there been a release since this was fixed? I'm getting audit warnings despite this apparently being fixed in May?

Edit: I now see the fix is only in 3.0 branch, which is in alpha and which I assume will not be a simple upgrade when it is ready. Is there any chance of the fix getting into the 2.0 branch? I don't have a sense of how complicated the fix was.
