### ISSUE TITLE
A Discord server for Actix and Actix Web

### ISSUE THREAD

**Issue by naturallymitchell** [actix/actix-web#1545]
[Actix Discord Server](https://discord.gg/2A9h75V) could replace Gitter.

**Comment by robjtede** [comment]
Lack of threads on Discord still leaves something to be desired for a Q&A location.

**Comment by JohnTitor** [comment]
> Note: They told me that they made that Discord server and I **already** replied that we didn't treat it as _official_.

So, we already have the Gitter channel, and maintaining multiple places needs more resources, the actix team doesn't have now. Also, it should cause some confusion, e.g., "hm, where should I ask?" or "uhm, where should I answer?".
For questions, we can use the Gitter channel. For discussion, we can use the issue tracker (or if it should be private, we can use GitHub's team discussion).
You're too aggressive here. If we switch to Discord or something, we need to make a discussion with the team and update links and make an announcement, etc. before moving.
So it's very welcome to use Discord as _community_ but we don't consider it as an _official_ place.

Please DO NOT be a bad actor. I don't really want to moderate strictly here...

**Comment by naturallymitchell** [comment]
Rust, Tokio, and countless other OSS projects use Discord.  Why would you want to keep the community on Gitter?  It's horribly broken and not useful for much.

**Comment by robjtede** [comment]
I don't think we're fundamentally against Discord as a discussion place. The primary issue is that 90% of the discussion on Gitter is Q&A from folks new to the framework. Here's the main advantages over Discord for this purpose:

- Sign up is 0 hassle for anyone with a GitHub/GitLab account. The folks who are new are also the folks less likely to have Discord.
- Supports threaded conversations. This is important because it keeps the question parts at the top level and helps scanning back over the history quickly. In my own experiences with other projects' Discord servers, it's frustrating to see my question move so far back in the history without getting answered, buried within answers to other things; a less that ideal feeling for newcomers.
- The administration and moderation permissions are synchronised with GitHub teams; this new server would require manual management of moderators. At the moment, all the Actix contributors are merely users of the server who'd need to defer to yourself for deleting posts/new channels/name changes/other things that require permissions.

The other part of the problem, of course, is that this action was taken without any discussion with the contributors here. This issue could have been a contructive discussion where you outline your view on the advantages of Discord and we explain our view on why we tollerate Gitter. What actually happened was it is simply announced as a thing to both Gitter channels, all the main actix repos, the Tokio discord and Reddit. I wholy agree with @JohnTitor that this was too sudden.

**Comment by ibraheemdev** [comment]
There is now an official [actix discord server](https://discord.gg/NWpN5mmg3x)
