### ISSUE TITLE
actix-web losing race - see benchmarks, I also wonder if actix-web will be actively maintained or not?

### ISSUE THREAD

**Issue by shujaatak** [actix/actix-web#1624]
Check out the latest preliminary results here:
https://www.techempower.com/benchmarks/#section=test&runid=a21aa293-2b08-45bd-b997-b1d397024b51&hw=ph&test=fortune&a=2

 I am pointing to ntex-db.
Github repository: https://github.com/ntex-rs/ntex

**Comment by mocsy** [comment]
Actix web today, has a lot more runtime features than early versions had, yet only drogon-core beats it, and that only supports http 1.1.
As far as I know Actix web is still the fastest one if http 2 is considered, which should be as that helps a lot with real life page loads.

**Comment by shujaatak** [comment]
@mocsy I was pointing to ntex-db.
Github repository: https://github.com/ntex-rs/ntex

**Comment by JohnTitor** [comment]
I don't think we should put this topic on the issue tracker, what's the action we can take here? Actually, we (the actix community) are leaning toward safety rather than fast. And ntex is Nikolay's personal project.
Now, we could say actix is `passively-maintained` but we're happy to see any PRs and review them, of course.

**Comment by robjtede** [comment]
If I may put forward my view...

ntex, as a fork of actix with most of the original and problematic unsound code, is about where we expect in the rankings given what we've changed about actix' ecosystem since it was forked. This, at least to me, isn't a bad thing; our performance is still excellent.

Not to mention that in the "Single Query" section from the benchmark you linked, the "actix-pg" benchmark outperforms "ntex-db". We trade blows with ntex despite having a safer codebase. This is thanks to the foundationals of how the library works not about how much unsafe code we can squeeze a couple of CPU cycles out of.

"Losing race"? I think that sentiment does a disservice the great work the actix contributors and community have made over the last several months to improve the safety of the library while keeping performance at the high level that often attracts developers to actix in the first place.

**Comment by fafhrd91** [comment]
oh humans...

"single query" doesn't contain any "improvement" you and new community made. it is "unsafe". but you can check currently running bench it already contains latest releases. I brought actix to the top, but to keep it on top new community need at least some expertise in performance work. from your comment seems like ntex is a hostile fork of the cool open source framework, but you seem forgot who's name is in license file.

**Comment by robjtede** [comment]
I have the upmost respect for your work Nikolay and an honoured to be working on Actix now. Not trying to work against you here :/

A "hostile fork" is not how I'd describe it. My point was that we have slightly different priority lists and that Actix is hardly "losing" against ntex just because it is lower in some scores. We would expect a lower score than ntex based on some changes we've made.

However, I see the v3 beta bump was made after this issue was opened (thank you) so we will have another look soon.

**Comment by fakeshadow** [comment]
To be fair the last time I see the techempower benchmark actix is using the tokio-postgres fork from Nikolay. I believe the db performance could be lower if we stay on the release tokio-postgres(I'm not sure though).

I see this as an example how we can still work together and I consider ntex a good learning material for me too. I believe there is value in both the so called "safe" and "unsafe" approach of things.

**Comment by shujaatak** [comment]
@fafhrd91 Thank you so much for such a great open source project. Nikolay Kim, You have earned a very special place in the hearts of all of us who use your open source projects. Once again, THANK YOU! <3

@robjtede and other contributers, Thank you so much for contributing to this awesome project. Your contributions have made actix-web more refined, safer and the one which can be used with absolute confidence and peace of mind as it should be!

**Comment by mahdi-shojaee** [comment]
IMO actix-web is one of the brilliant projects in the Rust community. Imagine how pleasant it will be if @fafhrd91 come back to this nice project.
