### ISSUE TITLE
connection left open when spamming with garbage

### ISSUE THREAD

**Issue by aep** [actix/actix-web#164]
is it intentional  that the connection is left open on invalid http?
From a production perspective this seems pretty dangerous since it at least eats up file descriptors easily during a DOS.

**Comment by DoumanAsh** [comment]
What do you mean by garbage?
Do you send malformed HTTP requests toward server?

By defaullt Actix-web will rely on OS to shutdown TCP connection. See https://docs.rs/actix-web/0.4.10/actix_web/server/struct.HttpServer.html#method.keep_alive

**Comment by aep** [comment]
yes. 

```
while true; do echo  BLA; sleep 1; done | telnet 127.0.0.1 8080 
```

doesn't appear to ever close the connection.

**Comment by DoumanAsh** [comment]
@aep As per [RFC7230](https://tools.ietf.org/html/rfc7230#section-6.3)

>HTTP/1.1 defaults to the use of "persistent connections", allowing
   multiple requests and responses to be carried over a single
   connection.  The "close" connection option is used to signal that a
   connection will not persist after the current request/response.  HTTP
   implementations SHOULD support persistent connections.

So having connections persist by default seems to be the thing you're supposed to do.
The problem is that I'm not sure how it goes with intentionally malformed requests.

I think there should be no special treatment of connections over which we receive malformed requests.
Instead user of actix-web should consider setting appropriate KeepAlive timeout.

But let's wait for @fafhrd91 opinion

**Comment by fafhrd91** [comment]
connection should be closed in case of non well-formed http messages. if it is still open then it is a bug.

@aep could you provide your test data?

**Comment by fafhrd91** [comment]
please re-open when you get more info
