### ISSUE TITLE
Auto-Reloading Error 

### ISSUE THREAD

**Issue by benjamingb** [actix/actix-web#1722]
I am trying to run the example from the [manual](https://actix.rs/docs/autoreload/) 

```
use actix_web::{web, App, HttpRequest, HttpServer, Responder};
use listenfd::ListenFd;

async fn index(_req: HttpRequest) -> impl Responder {
    "Hello World!"
}

#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    let mut listenfd = ListenFd::from_env();
    let mut server = HttpServer::new(|| App::new().route("/", web::get().to(index)));

    server = if let Some(l) = listenfd.take_tcp_listener(0).unwrap() {
        server.listen(l)?
    } else {
        server.bind("127.0.0.1:3000")?
    };

    server.run().await
}
```

but I have the following error: 

```
 Compiling app v0.1.0 (/mnt/sd2/www/my-api-new/app)
    Finished dev [unoptimized + debuginfo] target(s) in 3.42s
     Running `target/debug/app`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: "fd 3 is not a valid tcp socket" }', app/src/main.rs:13:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Panic in Arbiter thread.
[Finished running. Exit status: 101]
```

## Your Environment

* Rust Version (I.e, output of `rustc -V`): rustc 1.46.0 (04488afe3 2020-08-24)
* Actix Web Version: "3.1.0"
* SO: Ubuntu 20.04

**Comment by robjtede** [comment]
> app/src/main.rs:13:61

Line 13 is a listenfd line so problem is not in actix code. For that reason I'm going to close this.

Also that page was removed from the docs contents and only accessible now because it's a leftover static page. Any way in my experience it's not worth the hassle and just using cargo-watch (`cargo watch -x run`) is plenty good enough for "auto-reloading" purposes.
