### ISSUE TITLE
Actix losing track of client connections

### ISSUE THREAD

**Issue by cholcombe973** [actix/actix-web#1759]
## Expected Behavior
Clients that reuse the same TCP connection to make multiple requests should receive responses to each request made.

## Current Behavior
I'm not entirely sure why this is happening yet but with tcpdump I'm seeing some strange behavior where a client is making a PUT then GET then HEAD then DELETE request all on the same tcp connection. With tcpdump I'm seeing the first head request never get a response, keep-alive is exceeded and the connection is closed. A new connection is opened with a second head request which the server then processes like normal. My best guess is that somehow actix is losing track of the first request. 

## Possible Solution
I don't have any possible solutions yet. So far I've been only able to recreate the bug with a java netty client. It issues near simultaneous requests for the GET/HEAD portion of the flow. 

## Steps to Reproduce (for bugs)
Here's the server code:
```   
let http_server = HttpServer::new(move || {
                App::new()
                    .app_data(data.clone())
                    .service(
                        web::scope("/")
                            .route("*", web::get().to(get))
                            .route("*", web::delete().to(delete))
                            .route("*", web::put().to(put))
                            .route("*", web::head().to(head)),
                    )
            })
            // 2HR graceful shutdown timeout
            .keep_alive(5)
            .shutdown_timeout(7200);
   http_server
       .bind(&format!("0.0.0.0:{}", config.listen_port))?
       .run()
       .await?;
```
The head request looks roughly like this:
```
async fn head(
    request: HttpRequest,
    storage: web::Data<Storage>,
) -> HttpResponse {
 let object_name = Path::new(&path)
        .file_name()
        .unwrap_or_default()
        .to_string_lossy();
    let p1 = path.to_string();
    // Spin up a thread to await for storage to respond
    let index = web::block(move || storage.head(&p1)).await;
    match index {
        Ok(index) => match index {
            Some(index) => {
                client_response = HttpResponse::Ok();
                let mut bytes = BytesMut::with_capacity(index.size as usize);
                // Build an in-memory buffer of 0's with the correct size
                for _ in 0..index.size {
                    bytes.put_u8(0);
                }
                // TODO: Build a struct that can serve blocks of 0's instead of building of everything up at once
                return client_response
                    .header(actix_web::http::header::ACCEPT_RANGES, "bytes")
                    .no_chunking(index.size)
                    .force_close()
                    .body(actix_web::body::Body::Bytes(bytes.freeze()));
            }
           // Error handling here
          ...<snip>...
        },
    }
}

```
1. Start up actix and listen for client http connections.
2. Client issues a `PUT`, `GET`+`HEAD` almost at the same time, and then finally `DELETE` requests
3. tcpdump shows the keep-alive is exceeded, the client connection is closed. Another one is opened and `HEAD` responds normally
4. http headers for HEAD method:
```
User-Agent: health_tester\r\n
Host: test-server01\r\n
transfer-encoding: chunked\r\n
```

## Context
I have a client that's making these requests to verify the existence of a file. When the head request hits the keep-alive timeout it causes the client to have to reissue the request slowing everything down.

This seems possibly related to: https://github.com/actix/actix-web/issues/236

## Your Environment
CentOS Linux release 7.8.2003 (Core)

* Rust Version (I.e, output of `rustc -V`): 1.47.0
* Actix Web Version: 3.1.0

**Comment by glueball** [comment]
I'm facing a similar issue. In my use case, I have a Rust (reqwest) client that in some acts as a gateway to a set of services written using actix. So my setup is basically client -> gateway (reqwest) -> service (actix). 

In certain moments, the client needs to perform several (5-10, depends on what the user is doing) requests in quick succession, and every now and them some of the requests never get an answer.

To troubleshot the issue I made a client script that sends identical requests in fix intervals. When the scripts sends a requests relatively slowly (one every 200ms or so), all requests seem to work just fine (around 1-5ms each). But when the client goes faster, under 100ms or so, I start to see requests that time out. So it seems the problem seems to happen when the client reuses a connection really quickly before the next requests. 

To further test, repeated the same tests replacing the actix service with a nginx serving a static file. It seemed to work just fine even at high speeds. Also works fine when disabling keep-alive (in my case, I disabled keepalive at the gateway, so it didn't reuse connections to actix).

 As cholcombe973 said, this seems very similar to the symptoms of #236.

### Environment

Rust: 1.47,
Actix: 3.2.0
Both the actix service and the gateway (sending requests to the service using reqwest) are in their respective docker containers linked by a docker network, using docker v19.03.13 for windows with the WSL2 backend (but the same issue seems to happen in the productions server, which are ubuntu)

**Comment by robjtede** [comment]
If you're thinking it's related to 236, a keepalive issue, do you notice any change in behavior when disabling keepalive?

**Comment by glueball** [comment]
Hey @robjtede,

Thanks for taking a look into this.  

Yes, absolutely. I already had verified that disabling keep alive at the client side (a gateway, in my case) solved the issue. For me it was easier to disable it at the single gateway rather than in the several services. But figured guess that it'd be more useful for you to test the other way around. 

So I re-enabled keep-alive connection polling client side and disabled it in one of our actix-web services (`.keep_alive(KeepAlive::Disabled)`). The results are the same: I have yet to see actix "loosing" a request with keep-alive connections disabled (either client or server-side).

If this is not related to #236, at least the symptoms are very similar. I have noticed that failures are more likely to happen on the first burst of requests, just after server-startup or after having waited the keep-alive timeout. My interpretation of that is that in this situation the pool of established connections is almost empty, so it is more likely that a single connection to be reused very quickly. But that is just a guess, since I'm not familiar with the internals of reqwest/hyper (the library I use for making requests), nor with actix's.

**Comment by cholcombe973** [comment]
This turned out to be an issue with the actix configuration I created. When I explicitly disabled KeepAlive the expected behavior arose. Everything is working normally now for me.

**Comment by pickfire** [comment]
@cholcombe973 Should this be closed?

**Comment by cholcombe973** [comment]
Yeah

**Comment by dmitryb-dev** [comment]
Just performed some benchmarks on Actix. And I faced a similar problem;
I was running JMeter with 1000 parallel connections with 5 requests per connection and get 3% of errors with "Server failed to respond".
Disabling keep-alive in JMeter didn't help.
But disabling keep-alive on the server-side with `.keep_alive(KeepAlive::Disabled)` solved the problem and I started to get 0% of errors.
Seems some problem with keep-alive still exists, but I don't see open issues regarding this.
Or maybe I'm wrong and this is expected behavior?

**Comment by robjtede** [comment]
@dmitryb-dev Are you able to share more info about your test setup?

Also valuable would be similar tests using tools such as `ab` or `wrk` to see if they produce the same behaviour (and what config was used in these tests & OS/version.

**Comment by dmitryb-dev** [comment]
@robjtede Yes, I'm running a dockerized app on a Linux server with 1 core and 2GB of memory, docker file looks like this:
```
FROM rust:1.48.0 AS builder
...
RUN cargo install --path .
```
App code with actix-web: "3.3.2":
```
async fn test(...) -> Json<UserOrderEntity> {
      // Here I'm doing INSERT + SELECT FOR UPDATE + UPDATE with sqlx in transaction
      ...
      Json(UserOrderEntity {
         id: 1,
         ...
      })
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
   ...
    HttpServer::new(move || {
        App::new()
            .route("/order", web::post().to(test))
    })
        // .keep_alive(KeepAlive::Disabled)
        .max_connection_rate(10000)
        .bind("0.0.0.0:8081")?
        .run()
        .await
}
```

Checked with wrk:
`wrk -t1000 -c1000 -d10s -s bench.lua http://...:8081/order`
It produces next for keep-alive disable commented out:
```
  3688 requests in 10.12s, 669.80KB read
  Socket errors: connect 0, read 41, write 0, timeout 255
Requests/sec:    364.33
```
And this for disabled keep alive:
```
  1410 requests in 29.32s, 282.28KB read
  Socket errors: connect 0, read 0, write 0, timeout 355
Requests/sec:     48.09
```
And to be honest I'm not sure that results received with wrk 100% correct, because when I increased time for test, I received a lot of read errors for both cases. So I think we should consider wrk results not relevant for my topic. But this isn't happening in JMeter. In JMeter I receiving only timeouts sometimes but not read errors in case of keep-alive disabled. And read errors happened even under smaller load (100-200 threads instead of 1000) in case for keep-alive enabled. It was unclear for me what errors I'm receiving in wrk, so this was a reason, why I decided to try JMeter.

Also maybe worth mentioning that I'm also tested the same case in Java app (with Spring boot) and it gives slightly smaller throughput (10-20%) but I've always get zero errors in JMeter, but wrk gives the same read errors as in case of actix.

**Comment by dmitryb-dev** [comment]
@robjtede Just tried to increase keep-alive to 30s. It helped, now I'm receiving 0% of errors. And also need to say that performance is amazing. So I think the problem was in configuration or maybe just in my not perfect knowledge of how keep-alive works internally.
