### ISSUE TITLE
Extract path arguments in middleware

### ISSUE THREAD

**Issue by danielalvsaaker** [actix/actix-web#1784]
Extracting path arguments in middleware does not work like I expected. Using an extractor like actix_identity works, but not web::Path.

## Expected Behavior
`actix_web::web::Path::<String>::from_request(request, payload)` in a service call returns path argument(s).

## Current Behavior
Returns "wrong number of parameters: 0 expected 1".
`actix_identity::Identity::from_request(request, payload)` works.

Output of `request.match_info()`, `request.match_pattern()` and `actix_web::web::Path::<String>::from_request(request, payload)` from inside the service call:
![Screenshot 2020-11-10 at 08 21 03](https://user-images.githubusercontent.com/30574112/98642499-dc36a000-232d-11eb-905b-17f5c5c05fff.png)

## Steps to Reproduce

1. Implement a middleware service, with the Path extractor
2. Call the middleware on a route which takes a path argument

## Context

I'm trying to implement authenticated paths based on username of the authenticated user and path argument.

## Your Environment

* Rust Version: 1.46.0
* Actix Web Version: 3.2.0

**Comment by zdannar** [comment]
I just updated from actix_web 2.0.0 to 3.2.0 and I am also having issues with path extraction.  This is the webpath to my handler, path: web::Path<(u8, u32, u32)>, now it unpacks the path it a single tuple.  /v2/some/path/{z}/{x}/{y}.  Not sure it is related, but it could be.

**Comment by robjtede** [comment]
@zdannar check out the migration document in the repo. this was one of the breaking changes made to Path.

**Comment by zdannar** [comment]
@robjtede Thanks.  I just figured out there is a difference.

**Comment by tl8roy** [comment]
So I'd like to reopen this issue as while @danielalvsaaker got it working, they did so in a less optimal way. (But I am grateful because I was banging my head against this issue)
URL that was used: ```/user/{id}```
The middleware call function:
```
    fn call(&mut self,mut req: ServiceRequest) -> Self::Future {
       
        let id= req.match_info().query("id");
        println!("This doesn't work: {:?}", id);

        let fut = self.service.call(req);
        Box::pin(async move {
            let res = fut.await?;
            let id= res.request().match_info().query("id");
            println!("This does work: {:?}", id);
            Ok(res)
        })
}
```
While succeeding to parse the URL at the response stage would technically solve my particular use case, I would think that the path should work before the request is processed.

**Comment by toadslop** [comment]
I'm also having this issue. To add some more context, if you call `req.match_pattern()` you get the match pattern fine, so it's not a question of whether or not the pattern is there -- it's just not getting processed until after the middleware function is called.

**Comment by robjtede** [comment]
Couple of non-obvious things at play here:

- The match patterns are processed progressively as the request passes through the routers and sub-routers.
- Middleware functions **wrap** routers.

So, match patterns being unavailable before routers are invoked is by design; it's a trade-off for flexibility.

There should be some combination of calls possible to emulate the routing using [`ResourceDef::capture_match_info`](https://docs.rs/actix-web/latest/actix_web/dev/struct.ResourceDef.html#method.capture_match_info).

A new issue should be opened for any more discussion.
