### ISSUE TITLE
How to implement ResponseError for r2d2::Error and diesel::result::Error?

### ISSUE THREAD

**Issue by spease** [actix/actix-web#197]
Is there any way to do this? The examples just seem to use panics, which doesn't seem like good practice.

**Comment by brandur** [comment]
Hey @spease, did you see [this section of the user guide](https://actix.rs/book/actix-web/sec-5-errors.html)?

In particular, the combination of `map_err` with actix-web's error helpers might be enough to get you off the ground. Here's the example usage from the guide:

``` rust
#[macro_use] extern crate failure;
use actix_web::*;

#[derive(Debug)]
struct MyError {
   name: &'static str
}

fn index(req: HttpRequest) -> Result<&'static str> {
    let result: Result<&'static str, MyError> = Err(MyError{name: "test"});

    Ok(result.map_err(|e| error::ErrorBadRequest(e))?)
}
```

For more serious production use, you'd probably want to define a set of custom errors using either [`error-chain`](https://github.com/rust-lang-nursery/error-chain) or [`failure`](https://github.com/withoutboats/failure), implement `error::ResponseError` on them, then make sure to map your errors from other crates like `r2d2::Error` onto one of them. This would give you direct control over how various problems will bubble up to a client as an HTTP response. The guide also has a good example of that.

And one final thought: it might be appropriate to leave something as low level as an `r2d2::Error` to manifest as a 500 because this more than likely is representative of an internal problem rather than one that an HTTP client created for themselves.

**Comment by spease** [comment]
Thanks. I'm using this for a small-scale project, but I'm trying to build it with production quality. So if I use an example like you provided, is there a risk of sensitive information being exposed to the outside world via an error message?

Since diesel and r2d2 are both 'recognized' by actix_web, imho it would make sense to provide From traits for their error messages that are appropriate to production. It's effectively impossible to do this in an external crate due to the traits restriction, and it drastically cuts down on the knowledge needed to just get started. It doesn't prevent someone from overriding it with something specific to their project if they want and it doesn't seem like there's any backwards compatibility concern since the code simply flat out won't compile (and it's impossible to define those traits in an external crate).

EDIT: Or implement the ResponseError trait for the r2d2/diesel errors, same reasons.

**Comment by brandur** [comment]
> Thanks. I'm using this for a small-scale project, but I'm trying to build it with production quality. So if I use an example like you provided, is there a risk of sensitive information being exposed to the outside world via an error message?

I think that _probably_ not, but this is in no way guaranteed. Beyond sensitivity though, I think it's worth considering that these classes are very much internal, and surfacing the problem that they're describing is probably beyond what a user should be told about because the responsibility of the fix is an entirely the onus of the service operator.

For example, the most likely r2d2 error you're going to encounter is probably something like a timeout (if your target DB is down), or connection exhaustion (too many connections in Postgres or the like). Neither of these problems are actionable by the user.

What I would do is make sure they're converted to a 500 with a generic error message, and that I'm notified so that I can start getting a fix in place.

> Since diesel and r2d2 are both 'recognized' by actix_web, imho it would make sense to provide From traits for their error messages that are appropriate to production.

I should make it clear first of all that I'm not a major contributor here, but IMO, actix-web providing default coercing for Diesel/r2d2 errors would be a boundary violation. Beyond that, it seems to me like good hygiene to me to at least force users of actix-web to _think_ about how they're going to handle these errors rather than defaulting to anything.

If you're looking for a pretty nice and low-effort solution, you might consider specifying some foreign links with [error-chain](https://docs.rs/error-chain/0.11.0/error_chain/):

``` rust
error_chain!{
    foreign_links {
        Database(::diesel::result::Error);
...
}
```

You could then implement `ResponseError` on the `Error` type that it produces:

``` rust
impl error::ResponseError for Error {
    fn error_response(&self) -> HttpResponse {
        ...
    }
}
```

**Comment by fafhrd91** [comment]
@brandur would you, based on your response, add sections to user guide?

**Comment by brandur** [comment]
@fafhrd91 Yes! Moving this to my inbox so that I'll remember to do it this weekend.

**Comment by brandur** [comment]
Finally got around to this (2.5 weeks late, hah). Added a PR here: https://github.com/actix/book/pull/5

**Comment by fafhrd91** [comment]
thanks!
