### ISSUE TITLE
why are responders no longer async ? 

### ISSUE THREAD

**Issue by ta3pks** [actix/actix-web#2120]
## Expected Behavior
Responders to be async so some extra things can be done at that stage
## Current Behavior
Responder trait no longer has a associated future
## Possible Solution
I dont know what this happened in the first place

## Context
I had responders doing some lookups before returning which is no longer possible which requires rewrite and rethink of the entire app

**Comment by fakeshadow** [comment]
Responder is just a help trait for construct a Response. Making it async is unnecessary and bloat the code with a lot of future types does nothing rather than unwrap an option in a poll method.

If you have a lot of logic in responder trait. You can move them into handler or use another trait to bridge handler and responder.

**Comment by fakeshadow** [comment]
For example your code can be
```rust
impl OpLoginResp {
    async fn respond_to(&req: HttpRequest) -> Result<HttpResponse, Err> {
        
    }
}
```

And call this method explicitly in handler before return. By doing this you get stack future instead of box and if you factor in you don't have to impl a trait with 3 associate types and import one boxfuture type(Or pin/future type). It actually reduce your code amount and reduce your heap allocation.

**Comment by ta3pks** [comment]
@fakeshadow seems like this solved the issue but added a ton of verbosity.

**Comment by fakeshadow** [comment]
Well it really does not. 
You have one less trait to impl. You have less trait/type import. You inline your async code and reduce heap allocation. It make your code simplier and more performant.

BTW I also catch a bug by refactoring Responder trait. https://github.com/actix/actix-web/pull/2093. The context here is if you wrap non future type and use them in async context. clippy would have a very hard time to catch vars that are not used. This is why this bug exists for a very long time without noticed.

This change improves your code quality in general but maybe in a foruceful way. You just have to look at what you gain from it rather than focusing on you have to make some changes to it.
