### ISSUE TITLE
Panicked at 'System is not running' when test with `test::start`

### ISSUE THREAD

**Issue by arniu** [actix/actix-web#2223]
When running the [example], the thread panicked at 'System is not running'.

## Steps to Reproduce (for bugs)

Run the [example] with `actix-web` 3.x installed. 

## Your Environment

* Rust Version (I.e, output of `rustc -V`): 1.52.1
* Actix Web Version: 3.3.2

[example]: https://docs.rs/actix-web/3.3.2/actix_web/test/fn.start.html#examples

**Comment by ibraheemdev** [comment]
what version of actix-rt are you using?

**Comment by arniu** [comment]
actix-rt 2.x

**Comment by ibraheemdev** [comment]
well that is the problem then. actix-web 2.x does not use actix-rt 2.x.

**Comment by bodo-hugo-barwich** [comment]
I've suffered from the same issue when running automated tests in the _GitHub Workflow_ environment.
A test that worked fine in the local development environment produced an error in the automated workflow:
https://github.com/bodo-hugo-barwich/actix-alerting-email/runs/5530098813?check_suite_focus=true
```
failures:

---- tests::test_send stdout ----
thread 'tests::test_send' panicked at 'System is not running', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/system.rs:78:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::test_send
```

According to the comment above I reviewed the dependencies and it turned out that there were **2 different versions** of the crate `actix-rt` present:
```
  Downloaded actix-web v3.3.3
  Downloaded actix-rt v1.1.1
  Downloaded actix-rt v2.7.0
  Downloaded actix-test v0.0.1
```
I think this came from crossed dependencies with `actix-test` which I included in `Cargo.toml` without concrete versioning.

So, I pinned the `actix-rt` version according to the documented dependencies at:
https://docs.rs/actix-web/3.3.3/actix_web/index.html
I also removed unused dependencies.
That resulted that there are no duplicated versions present in the system:
https://github.com/bodo-hugo-barwich/actix-alerting-email/runs/5535252291?check_suite_focus=true
```
  Downloaded actix-web v3.3.3
  Downloaded actix-rt v1.1.1
```
and the test succeeded.
