### ISSUE TITLE
Panic in `NormalizePath` when presented Uri is in authority form

### ISSUE THREAD

**Issue by Eijebong** [actix/actix-web#2240]
When running the following code:

```rust
use actix_web::{
    middleware::{self, normalize::TrailingSlash},
    rt, App, HttpServer,
};

fn main() {
    let mut runtime = rt::System::new("test");
    let server = HttpServer::new(move || {
        App::new()
            .wrap(middleware::NormalizePath::new(TrailingSlash::Trim))
        }).bind("127.0.0.1:8888").unwrap().run();

    runtime.block_on(server).unwrap();
}
```

I get panics like this:

```
thread 'actix-rt:worker:0' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidUriParts(InvalidUri(SchemeMissing))',
/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/middleware/normalize.rs:149:46
```

with requests like this: `GET eh HTTP/1.1` (notice the missing `/`)

**Comment by thalesfragoso** [comment]
Should we just skip normalizing if the path is empty ? Or `TrailingSlash::Always` makes sense for an empty path ?

**Comment by robjtede** [comment]
path cannot be empty according to http spec

edit: though potentially doable still, an empty path should be converted to / according to client spec

**Comment by robjtede** [comment]
Following discussion on [Discord](https://discord.com/channels/771444961383153695/771447545154371646/849809487706849280)...

In the presented test case (`GET eh HTTP/1.1`), `eh` is not a path since all paths must start with a forward slash. It is being interpreted as an authority form (see https://datatracker.ietf.org/doc/html/rfc7230#section-5.3.3) and as such the NormalizePath middleware should do nothing in such cases.
