### ISSUE TITLE
Does actix-web build/compile for ARM cross complier for armv7-unknown-linux-gnueabihf

### ISSUE THREAD

**Issue by snahmad** [actix/actix-web#2326]
cargo build --target=armv7-unknown-linux-gnueabihf fails to build.

however it build and run for Linux x86

**Comment by robjtede** [comment]
Firstly, ARM targets are not officially supported.

In order to get any sort of advice at all, you will need to provide much more information than that since no one on the team has such a device.

**Comment by realaravinth** [comment]
Cross-compilation with [cross](https://github.com/rust-embedded/cross) is a painless experience. It comes with dependencies required for cross-compilation neatly bundled in the form of a Docker image. 
Cross's UX is very similar to cargo. So

```bash
cargo build --target=armv7-unknown-linux-gnueabihf 
```
would become

```bash
cross build --target=armv7-unknown-linux-gnueabihf
```

**Comment by asonix** [comment]
While arm targets are not officially supported, I would like to mention that I produce armv7-unknown-linux-gnueabihf, armv7-unknown-linux-musleabihf, aarch64-unknown-linux-gnu, and aarch64-unknown-linux-musl builds for a few projects I maintain, which depend on actix-web. I have yet to run into an issue caused by the architecture
