### ISSUE TITLE
Consider remove Clone for HttpRequest

### ISSUE THREAD

**Issue by Kilerd** [actix/actix-web#2561]
While trying to write a middleware which do some async logic and store result into Request::extensions like do authentication and store user instance.

and I try to split `ServiceRequest` into parts and get `HttpRequest`, so that I can clone one of `HttpRequest` for storing data, and then wrap parts back to `ServiceRequest`

My Code is like:
```rust
fn call(&self, req: ServiceRequest) -> Self::Future {
        info!("in authentication service ");
        let (http_request, payload) = req.into_parts();
        let cloned_request = http_request.clone();

        let wrapped_request = ServiceRequest::from_parts(http_request, payload);
        let call_fut = self.service.call(wrapped_request);
        Box::pin(async move {
            // async logic here
            cloned_request.extensions_mut().insert(123i32);
            call_fut.await

        })
    }
```
and I try to get the extension in controller like
```rust
 let x = request.extensions();
 let option: Option<&i32> = x.get();
```
but it panic on `thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Option::unwrap()` on a `None` value', /Users/xinchen/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.18/src/request.rs:140:43`

so I dig into the reason, I found that maybe the drop of `HttpRequest` cause it, and there is a comment for `HttpRequest`.
> Invariant
> `Rc<HttpRequestInner>` is used exclusively and NO `Weak<HttpRequestInner>` is allowed anywhere in the code. Weak pointer is > purposely ignored when doing Rc's ref counter check. Expect panics if this invariant is violated.

so why not just considering remove `Clone` derive for `HttpRequest` and add a pub in crate function for clone the `HttpRequest`?

## Your Environment

- Rust Version (I.e, output of `rustc -V`): rustc 1.57.0 (f1edd0429 2021-11-29)
- Actix Web Version: 4.0.0-beta.18

**Comment by fakeshadow** [comment]
Why do you think your code have anything to do with `Weak` type? How can you even get a `Weak` type it's not possible from public interface.

Your problem is most likely due to misunderstanding how futures work in Rust.
Take this for example:
```rust
fn call(req: Rc<Option<u32>>) -> impl Future<Output = ()> {
    req.unwrap();
    // only code inside async is lazy. Everything above already happen at call site or even inlined.
    async { }
}

let a = Rc::new(None);

let fut = call(a.clone());  // your code panic here

a.get_mut().unwrap() = Some(123) ;

fut.await;
```

In your case to avoid footgun like this you would always prefer call your child service's future in lazy way. This would make sure everything always happen lazy when you need certain order especially when you don't know how the child service would execute. Take this example as reference:
https://github.com/actix/examples/blob/master/basics/middleware/src/read_request_body.rs

**Comment by fakeshadow** [comment]
#2562 would help resolve footgun like this.

**Comment by Kilerd** [comment]
cool, I even don't know Service generic can be wrapped with RC and REFCELL, so that service can be cloned can moved into async block

**Comment by fakeshadow** [comment]
yea it's a pattern we have to use due to async Rust's limitation on lifetime. It's the same reason we have to make `HttpRequest` impl Clone so it can be used in similar fashion like inside `FromRequest` trait.

btw since you are using actix-web 4.x beta you can go with a more relax pattern and remove the `RefCell`. `Rc<S: Service>` would be enough for most case.

**Comment by Kilerd** [comment]
cool, thx a lot.

**Comment by robjtede** [comment]
ye this is a non-starter, we just need to document the restriction better

**Comment by XX** [comment]
Actual example here: https://github.com/actix/examples/blob/master/middleware/middleware/src/read_request_body.rs
