### ISSUE TITLE
Use `&mut self` instead of `&self` for Middleware trait

### ISSUE THREAD

**Issue by fafhrd91** [actix/actix-web#263]
i think we should switch to `&mut self` for Middleware trait, it is safe

**Comment by joshleeb** [comment]
I'd like to give this one a shot 😄

I started playing around with changing `&self` to `&mut self` for the `start` function of the `Middleware` trait. 

It looks the `mws: Rc<Vec<Box<Middleware<S>>>>` value in `PipelineInfo`, `ComposeInfo`, and similar structs will need to be changed to `Rc<RefCell<Vec<Box<Middleware<S>>>>>` or `Rc<UnsafeCell<Vec<Box<Middleware<S>>>>>`. I mention `UnsafeCell` because it's used with `req: UnsafeCell<HttpRequest<S>>`.

I don't have a heap of experience working with `RefCell` (and even less with `UnsafeCell`) so I'm not sure if this is the best way to implement this change. 

@fafhrd91 WDYT? Or is there a better way to do this?

**Comment by fafhrd91** [comment]
let's use `RefCell`. don't forget to update change log.

thanks!

**Comment by fafhrd91** [comment]
fixed by #267

**Comment by fafhrd91** [comment]
@joshleeb what to work on something else?

**Comment by joshleeb** [comment]
Yea! What have you got in mind?

**Comment by fafhrd91** [comment]
1. there is bug in middleware handling #255  2 and 3 points
2. #254  - this one is more involved

**Comment by joshleeb** [comment]
Great 😄 thanks @fafhrd91
