### ISSUE TITLE
Return errors from stream as responses

### ISSUE THREAD

**Issue by junbl** [actix/actix-web#2719]
When I send data with a `streaming` payload, the stream is required to have a `Item = Result<Bytes, E>` signature. However, when errors are encountered mid-stream, the response fails and just leaves the partial data.

Ideally, these errors would be sent to the client (requiring `Item = Result<Bytes, impl ResponseError>` or similar). If that's not feasible, it'd be great to at least see these errors logged to the logging middleware, in the same way that errors are currently logged as "Error in reponse: {}" independent of what gets sent to the client.

**Comment by fakeshadow** [comment]
You can't magically insert an error to a http body unless itself can be considered part of the body.In that case it should go to `Bytes` variant. 
The streaming error path is left only for server internal error which must not reach to client.

For logging stream error it's possible and perferable from logger middleware.

**Comment by fakeshadow** [comment]
I could be stating it in a wrong way. Logger middleware does not log stream body error right now and I meant it would be nice for an option to enabling it.

That said this circle back to an old question: Should the error logging be at web level or http? This is a question because http2 would log stream error inside actix-http(not for http1). Which could result in an overlapping error log if there is another one just added in the web layer.

**Comment by junbl** [comment]
That would work for me personally!

I was thinking there was a way to replace a response with an error or ok after it was sent, but I probably just misread the docs for 100 Continue lol. Just `debug!()`ing the errors when they come through seems like an easy and helpful feature to add to me.
