### ISSUE TITLE
Responder for tuples

### ISSUE THREAD

**Issue by fafhrd91** [actix/actix-web#277]
here is idea. we can use tuples for response generation, something like:

```rust
fn index(path: Path<..>) -> impl Responder {
    (StatusCode::OK, Json::new(model))
}
```

or 

```rust
fn index(path: Path<..>) -> impl Responder {
    (StatusCode::OK, (http::CONTENT_TYPE, "plain/json"), Json<MyStruct>)
}
```
order should not matter

```rust
fn index(path: Path<..>) -> impl Responder {
    ("Welcome!", StatusCode::OK, (http::CONTENT_TYPE, "plain/text"))
}
```

@mitsuhiko @DoumanAsh thoughts?

**Comment by DoumanAsh** [comment]
One thing that bothers me is that it might be quite difficult to make all components of tuple generic.

What I can think as mandatory arguments are:
- Status code
- Body(or no body)

Everything else can be described as generic `HttpRequestPartBuilder` which would let's say have method that takes `&mut HttpRequest` and modifies it accordingly

The problem is that can we make all elements of tuple completely generic and therefore optional? 
e.g. can we omit things like `StatusCode`?
I actually don't want to allow it since it is clearly error prone as normally user would want to respond with proper code

**Comment by joshleeb** [comment]
The first example could be useful, as it seems like that is a common style of response, but for the most part I agree with @DoumanAsh. 

Looking at the examples above I am also required to think a bit more to determine what each element of the tuple is. 

I do think this makes sense in a limited capacity, such as when defining multiple headers:

```rust
fn index(req: HttpRequest) -> HttpResponse {
    HttpResponse::Ok()
        .headers(vec![
             ("X-TEST", "value"),
             (http::header::CONTENT_TYPE, "application/json"),
        ])
        .finish()
}
```

Or for building common responses, such as a response with a JSON body and status code.

But for this header example, it's already pretty similar to what we can currently do:

```rust
fn index(req: HttpRequest) -> HttpResponse {
    HttpResponse::Ok()
        .header("X-TEST", "value")
        .header(http::header::CONTENT_TYPE, "application/json")
        .finish()
}
```

**Comment by fafhrd91** [comment]
this method is just simple extension to what have already in form of Responder's, i.e. `Json<T>`
i see this as a simple form for returning `Json` with custom status code.

something like `Ok((StatusCode::CREATED, Json<MyStruct>))`

**Comment by fafhrd91** [comment]
too complex. we just need Response::with_status method which returns ResponseBuilder

**Comment by messense** [comment]
I think it would be nice to at least have an impl for `(T, StatusCode)`(or `(StatusCode, T)`) since it's quite common to respond with custom status code.
