### ISSUE TITLE
 Directory custom 404 Not Found response

### ISSUE THREAD

**Issue by uncotion** [actix/actix-web#286]
Hello,
When a file is not available in StaticFiles actix-web automatically shows 404 error without body, i want to show custom error but default_handler not working.
```
            .handler(
                "/static",
                actix_web::fs::StaticFiles::new("./static/")
                    .default_handler(p404)
                    .index_file("index.html"),
            )

```

```
fn p404(req: actix_web::HttpRequest) -> Result<actix_web::HttpResponse, actix_web::Error> {
    println!("{:?}lll", req);
    Ok(actix_web::HttpResponse::NotFound()
        .content_type("text/plain")
        .body("Not Found"))
}
```

**Comment by vharavy** [comment]
I have tried the code that you provided and everything works fine: I clearly see the output in the standard out (including the `lll` that is printed after the request (in `p404`) as well as custom body `"Not Found"` in your case (I have modified it to make sure).

Looks like this has been solved already.

**Comment by DJMcNab** [comment]
I can reproduce the bug that if a file is not present, a 404 page is given. The bug appears to be in:

https://github.com/actix/actix-web/blob/master/src/fs.rs#L697-L701

It appears that if the file cannot open, and error is returned, which I imagine will create an internal server error. The [`std::io::ErrorKind::NotFound`](https://doc.rust-lang.org/std/io/enum.ErrorKind.html#variant.NotFound) variant should be handled in order to manage this, by calling `io::Error::kind` on the returned error when `NamedFile::open` is called. I don't have time to implement this myself, but it should be a trivial fix.

@VHaravy, if the static directory doesn't exist, then the default handler is used as it should be. I suspect that is what you were experiencing.

Maybe 'good first issue' would be suitable?

**Comment by fafhrd91** [comment]
@DoumanAsh could you review this issue?

**Comment by DoumanAsh** [comment]
@fafhrd91 Errors  are handled on `0.7` by default handler but not in `1.0`

**Comment by fafhrd91** [comment]
open file error calls default handle in master
