### ISSUE TITLE
security header format not correct case causing failure

### ISSUE THREAD

**Issue by jpegleg** [actix/actix-web#2862]
Even if security headers are set in the appropriate casing, the actual headers become lowercase.
This results in other systems failing to detect critical security headers.

```
        // the resulting headers will look like these in the comment
             //strict-transport-security: max-age=31536000; includeSubdomains;
             //x-content-type-options: nosniff
             //x-frame-options: SAMEORIGIN
             //x-xss-protection: 1; mode=block
             // most checkers look for the formatting like how I entered them! Strict-Transport-Security not strict-transport-security
            .wrap(middleware::DefaultHeaders::new().add(("Strict-Transport-Security", "max-age=31536000; includeSubdomains;")))
            .wrap(middleware::DefaultHeaders::new().add(("X-Content-Type-Options", "nosniff")))
            .wrap(middleware::DefaultHeaders::new().add(("X-Frame-Options", "SAMEORIGIN")))
            .wrap(middleware::DefaultHeaders::new().add(("X-XSS-Protection", "1; mode=block")))

```

## Expected Behavior

The headers casing should be preserved.

## Current Behavior

Header casing is always lowercase.

## Possible Solution

Preserve casing in header configurations.

## Steps to Reproduce (for bugs)
1. Set a header in actix app as done above
2. Compile application
3. Run application and visit it
4. Check the headers (with a web browser: f12 then network tab reload, then click on a GET, then view Response Headers)

## Context
If a header is to be set as "X-Content-Type-Options" it should not be changed to "x-content-type-options".
Setting the header to lowercase may miss checks and requirements, causing failures.

## Your Environment
- rustc version:
rustc 1.63.0 (4b91a6ea7 2022-08-08) 
- Actix Web Version:
actix-web = { version = "4", features = ["rustls"] }
actix-web-lab = "0.17"

**Comment by fakeshadow** [comment]
No. You are wrong that most checkers are case sensitive and you are expecting actix-web to do the wrong thing.

http/1.1 header names must be case in-sensitive. See [rfc2616](https://www.ietf.org/rfc/rfc2616.txt) - section 4.2
http/2 header names must be lower case. See [rfc7540](https://datatracker.ietf.org/doc/html/rfc7540) - section 8.1.2
http/3 is the same as http/2. See[rfc9114](https://datatracker.ietf.org/doc/rfc9114) - section 4.1.2

That said for legacy system (which are built last century) and people prefer to do stuff in the wrong way. There is https://docs.rs/actix-web/latest/actix_web/dev/struct.ResponseHead.html#method.set_camel_case_headers api that you can force the header name to include uppercase (only for http/1 though becasue since http/2 the wrong doing is strictly forbidden by most implementations). 

Example:
```rust
let mut res = actix_web::HttpResponse::Ok().finish();
res.head_mut().set_camel_case_headers(true);
```

**Comment by jpegleg** [comment]
Thank you for responding! This is the information I needed, much appreciated.
