### ISSUE TITLE
The function app_data of web::ServiceConfig cannot persist

### ISSUE THREAD

**Issue by cj495840252** [actix/actix-web#3231]
Hello, When I made a router and add vector of shared data, the shared data is cannot persist. Because I only want share data for one router scope. 

## Current Behavior
for example, initially vector.len() == 3 ,when I post the url , The third time, the vector had been restore
<img width="265" alt="image" src="https://github.com/actix/actix-web/assets/63491689/7216867e-4735-46d0-a85f-3b479bde5a77">

## Code
I define a router with web::ServiceConfig and add it into App::new().configure .
<img width="903" alt="image" src="https://github.com/actix/actix-web/assets/63491689/d4e15602-500a-4685-b21b-47fe704951d9">

- Rust Version : 1.71.0
- Actix Web Version: 4.4.0

**Comment by robjtede** [comment]
I suspect you're passing in `tmp_articles` in a way that clones the data instead of sharing it. You need to construct that `Data<Mutex<T>>` outside of the `HttpServer::new` closure in order to share it across all workers. See: https://docs.rs/actix-web/latest/actix_web/struct.App.html#shared-mutable-state
