### ISSUE TITLE
Re-export Bytes?

### ISSUE THREAD

**Issue by mqudsi** [actix/actix-web#391]
Is it possible for the actix-web crate to re-export the `Bytes` type so that a crate-level dependency on `bytes` is not needed?

**Comment by fafhrd91** [comment]
i am not sure about this.

@DoumanAsh thoughts?

**Comment by DoumanAsh** [comment]
This one is actually difficult one.
I'm not sure what is acceptable practice, but it may be convenient for user if we re-export external stuff that are exposed through public API to avoid potential compile errors (remember story with many reports on wrong actix or futures usage)

I don't think that `Bytes` would be such serious problem comparing to `futures` or `actix` dependency though.
But when we re-export particular component of external dependency it makes it difficult to navigate docs.
For example if we re-export only `Bytes` it will be part of `actix-web` docs API, so user might not be aware whether it is our own `Bytes` or `bytes::Bytes` without looking into source code.

Generally I would consider re-exporting only the whole crates to make it more obvious to reader of API documentation as otherwise it would be counter productive for users.

**Comment by mqudsi** [comment]
I wonder if exposing `Bytes` is even necessary? Can `&[...]` be used instead in the public-facing API? However, some of the places its used are e.g. a stream of `Bytes`, so that might make thing difficult.
