### ISSUE TITLE
#[derive(Message)] gives warning about implicitly using symbols from parent modules

### ISSUE THREAD

**Issue by Boscop** [actix/actix-web#419]
`#[derive(Message)]` gives warning about implicitly using symbols from parent modules,
but they are **NOT** from a parent module!

![image](https://user-images.githubusercontent.com/535593/43106836-bc983a7c-8eda-11e8-9b89-5efa18d7e4af.png)

**Comment by DoumanAsh** [comment]
I wonder if it is related to https://github.com/actix/actix-derive/pull/9

Do you use nightly too?
Try to upgrade `actix-derive`

**Comment by Boscop** [comment]
Yes, rustc 1.29.0-nightly (874dec25e 2018-07-21)

**Comment by Boscop** [comment]
I'm still using
```toml
actix = "0.5"
actix-web = "0.6"
```
though..

**Comment by DoumanAsh** [comment]
actix-derive itself is upgraded only recently and actix will depend on it in next release https://github.com/actix/actix/commit/7caf25523fbb6c6f3a5d8023d55e56129a752cf8

So to get rid of warning you'd need to eventually upgrade to 0.7

Other than that you can for now ignore it as it is already fixed in upstream

**Comment by fafhrd91** [comment]
fixed by actix-0.7.2
