### ISSUE TITLE
Should I implementing custom logging by middleware or state ?

### ISSUE THREAD

**Issue by wfxr** [actix/actix-web#469]
I need to get a logger from each request to do logging. It seams there are two way to I can use.

One way way is wrapping the logger(eg, an instance of `slog::Logger`) into a `State`.
The other is inserting the logger to `req.extensions()` in the `start` function by a `Middleware`.

Which way is better? Or more recommended?

**Comment by DoumanAsh** [comment]
Why wouldn't you make middleware that would handle logging itself?
Or is it specifically you want to access `slog` logger to log your requests?

I used in past `slog` and if I'm not mistaken it should be thread safe so I would advise to put into `State` to avoid unnecessary work with inserting into extensions
Make sure to wrap it in `Arc` before putting in state though so that it could be shared among all workers

**Comment by wfxr** [comment]
@DoumanAsh Thanks for your reply!

> Why wouldn't you make middleware that would handle logging itself?
Or is it specifically you want to access slog logger to log your requests?

Use the middleware to handle logging like the built-in `LoggerMiddleware` is not enough for me.

I have a lot of things to do during handling the request. I need to pass the logger to some other functions to do further logging while keep the logger's existed context like request id, session id etc.

So in this scenario use `State` is a better choice?

**Comment by DoumanAsh** [comment]
I see, to be honest while I like `slog` itself, especially since it provides async interface, but I prefer to use log [adaptor](https://docs.rs/slog-stdlog/3.0.2/slog_stdlog/) and [scope](https://docs.rs/slog-scope/4.0.1/slog_scope/) to provide more log like interface

>So in this scenario use State is a better choice?

Yes, I think it is the best place, but not that `State` is shared among workers so you should be careful about sharing it.

If you'd need a place to ask questions, visit our [gitter](https://gitter.im/actix/actix?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
