### ISSUE TITLE
Multipart field part and RFC 7578

### ISSUE THREAD

**Issue by jeizsm** [actix/actix-web#476]
There is a reason why multipart try to read Content-Length for field part?
RFC said it must be ignored https://tools.ietf.org/html/rfc7578#section-4.8

https://github.com/actix/actix-web/blob/56bc900a82e955fd58e2039695b4887d30386982/src/multipart.rs#L458-L468

**Comment by DoumanAsh** [comment]
@jeizsm But is`Content-Length` a MIME header as stated in RFC?

The only mime related headers are `Content-Type`, `Content-Disposition`, and `Content-Transfer-Encoding`
Length doesn't carry mime information

**Comment by jeizsm** [comment]
I just understood it like only this 3 headers is allowed, any other should be ignored. Maybe I'm wrong

**Comment by DoumanAsh** [comment]
I think it is for future when new headers that carry MIME data would appear.
`Content-Length` doesn't carry any MIME data in it so I don't think it is meant in this statement.

So at least it doesn't contradict to RFC I think.

But I guess we could look into existing practices for comparison

**Comment by DoumanAsh** [comment]
Ok... I considered it a bit, and I think in this case RFC whitelists allowed header so it is questionable to expect `Content-Length` in form-data field.

But it is optional as of now, so if client doesn't provide, we would just read up to boundary.

I don't think it is particularly problematic behavior as you might consider it as extension to RFC.
But multipart implementation allows you to omit this header as per RFC, so I think it is still ok with RFC.

What do you think @jeizsm ?

**Comment by jeizsm** [comment]
@DoumanAsh 
I just think should I implement it for client? Maybe behind feature flag. What benefits it brings? Perfomance? And how I understand it, Content-Length should be with headers and boundaries included?

**Comment by DoumanAsh** [comment]
@jeizsm I think it should be up to you.
RFC doesn't obligates for it to be implemented, it only helps server to faster find end of payload instead of looking for boundary.
So if you feel it is needed, then sure.

For example I recently been working on my HTTP client library and only followed spec when doing multipart as RFC doesn't requires it.

Considering this feature is not part of RFC I'm not sure would be actually beneficial, I never looked into other HTTP servers and whether they handle `Content-Length`

I close the issue if you don't mind, if you'll have questions ping me on gitter.
