### ISSUE TITLE
How to serve single file.

### ISSUE THREAD

**Issue by hbowden** [actix/actix-web#580]
I can't find anywhere in the docs on how to serve a single file with actix-web, I tried copying what other projects did and use namedFile however I cant get that to compile either. Here is the tutorial I followed: https://stevezeidner.com/blog/rust-actix-api/ . I adapted their code to the code below, however I get `expected 2 type arguments` as an error when I try to compile the code. So my issue is 3 fold, why doesn't this compile, can an example of serving a single file be added to the actix-web examples, and can the NamedFile docs show using NamedFile as a response?

```#![deny(warnings)]
extern crate actix_web;

use actix_web::{server, App, fs, HttpRequest};

fn favicon(req: HttpRequest) -> Result<fs::NamedFile> {
    Ok(fs::NamedFile::open("./favicon.png")?)
}

fn main() {
    server::new(|| {
        App::new().resource("/favicon", |r| r.f(favicon))
    })
    .bind("127.0.0.1:8080")
    .unwrap()
    .run();
}
```

**Comment by mzhang28** [comment]
Hi, in response to your first point, you're using Rust's standard `Result` object rather than actix's `Result` type alias. Typically, `Result` takes in two type arguments: the success type and the error type. The actix [Result](https://actix.rs/api/actix-web/stable/actix_web/error/type.Result.html) alias is defined:

```rs
type Result<T, E = Error> = Result<T, E>;
```

This way, `actix_web::error::Result<T>` actually becomes `std::result::Result<T, actix_web::error::Error>`. You can fix this by either explicitly including and using `actix_web::error::Result`, or by providing the second type argument `actix_web::error::Error`.

As to your second and third questions, I believe you can find the documentation here: https://actix.rs/docs/static-files/

**Comment by hbowden** [comment]
@iptq Thanks for the quick response it solved my problem! But why would actix-web make an alias of a core rust feature? Shouldn't a library not mess with language features?

**Comment by mzhang28** [comment]
It's actually a common pattern to do this; it helps you avoid adding the Error type on each Result, and makes some traits a bit simpler to write and use. It's just there for convenience.

Also, making an alias isn't really "messing" with the language features, either, since programmers would have to explicitly include it, like the guy in the blog post you followed did. I think you might've just missed that when you were following along.

**Comment by hbowden** [comment]
Looks like my last question is kinda related to this https://github.com/actix/actix-web/issues/251 I kept thinking I didn't need to import `Result` because its already in rust and I didn't think it I would have to import it again, but whatever I can move this conversation over to that other issue but thanks again for the help.

**Comment by schacker** [comment]
not working in actix-web@3.3.2

#[get("/favicon")]
async fn favicon() -> actix_web::Result<actix_files::NamedFile> {
    Ok(actix_files::NamedFile::open("static/favicon.ico")?)
}

**Comment by schacker** [comment]
> not working in actix-web@3.3.2
> 
> #[get("/favicon")]
> async fn favicon() -> actix_web::Result<actix_files::NamedFile> {
> Ok(actix_files::NamedFile::open("static/favicon.ico")?)
> }
----------------------------------
update  actix-files and actix-session, now  working well !
