### ISSUE TITLE
Streaming response

### ISSUE THREAD

**Issue by commial** [actix/actix-web#682]
Hi,

This is probably a noob question, but I didn't find the answer elsewhere.
I would like to implement a streaming HttpResponse, writing and flushing elements (let's say Bytes) to the client. The goal is to mimic what `bottle` (Python) does [when yielding](https://bottlepy.org/docs/dev/async.html).

I've tried to use the `Stream` trait, with `poll` sleeping and returning a few bytes each time. The struct is then used inside a [`streaming` call](https://docs.rs/actix-web/0.7/actix_web/dev/struct.HttpResponseBuilder.html#method.streaming).
Problem is, the data is only written as a whole block when the stream has no more data (end of polling).

Maybe the solution is to directly send my message through low level I/O, but hopefully there is a nicer solution.

**Comment by Baschdl578** [comment]
I get the same behavior.
For me, I wanted to send progress updates every 250ms.
Additionally, if you return an Async::NotReady instead of sleeping, the stream only gets polled every couple of seconds.
I think we need a way to notify the framework as soon as new data is available.
If I understand the documentation correctly, the current version of the "futures" crate would solve this by passing along a "Context" object that can be woken when data is ready. I'm not really sure though, the documentation is not very verbose. For reference:
https://docs.rs/futures/0.2.1/futures/trait.Stream.html

Maybe updating the dependency is the solution here?

**Comment by fafhrd91** [comment]
@commial you can use futures::unsync::mpsc
@Baschdl578 you have to understand how futures tasks work, you have to register task notification before returning NotReady and wake up task when new data is ready

**Comment by hurlebouc** [comment]
> @commial you can use futures::unsync::mpsc
Could you please be more specific? I have the same problem: actix only sends data when the stream ends.

**Comment by robjtede** [comment]
@hurlebouc given the very old age of this issue please open a new one with more details. thanks
