### ISSUE TITLE
How to run actix_web::server as a daemon?

### ISSUE THREAD

**Issue by xuchaoqian** [actix/actix-web#726]
There are no such options when I run actix_web::server.  
Another alternative is using nohup shell command.  
What should I do if I want to run actix_web::server as a daemon directly?

**Comment by 0x8f701** [comment]
@xuchaoqian  you can daemonize it using `systemd`, you just need to write a script. It shouldn't be included in a framework

**Comment by xuchaoqian** [comment]
@GopherJ Thank you! 
That's a choice. But it does't support macOS platform.

**Comment by Firstyear** [comment]
On macOS you can use launchd instead. I think that @GopherJ's trying to say that actix is not going to provide a daemon/execution model for you, because you either need to implement the forking yourself, or to use your OS platforms runtime to manage the service for you. Does that help? 
https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html

**Comment by xuchaoqian** [comment]
@Firstyear Thank you!

Inspired by @GopherJ and @Firstyear , maybe I will consider using supervisord, a cross-platform solution.
