### ISSUE TITLE
Should `time` be replaced with `std::time` for actix_web::cookie::Cookie max_age?

### ISSUE THREAD

**Issue by twharmon** [actix/actix-web#785]
It seems the time crate isn't maintained anymore.

**Comment by DoumanAsh** [comment]
`time` has some parsing functionality so you cannot replace it directly with `std::time`

**Comment by fafhrd91** [comment]
@twharmon Pr is welcomed

**Comment by fafhrd91** [comment]
we can migrate to chrono

**Comment by Kilerd** [comment]
Ummm, I'm facing this issue too, when setting Cookie's max_age, I need to add `time` to my dependence which actually we don't use to parse time instead of using `chrono`.
I think there are two choices, one is exposing `time:Duration` as public so that user does not need to add `time` to the dependency list. Or for the long term, replace it with `chrono`

**Comment by fafhrd91** [comment]
I think we should use `chrono`

**Comment by Kilerd** [comment]
okay, I can help

**Comment by fafhrd91** [comment]
i think `max_age` should accept number of seconds in `usize`. and `max_age_time` should accept chrono time

**Comment by Kilerd** [comment]
I'm working on it, but I don't think that `max_age` method should accept `usize` as the parameter. because  for cookies , it can accept `0` and `-1`.
 - `0` means delete the cookies right not
- `-1` means delete the cookies when the browser is closed

I perfer to use `isize`

**Comment by fafhrd91** [comment]
`max_age` now accepts value in seconds, max_age_time accepts time::Duration
