### ISSUE TITLE
http/2 with letsencrypt support automatically

### ISSUE THREAD

**Issue by cih-y2k** [actix/actix-web#82]
maybe this is useful (https://github.com/onur/acme-client)

**Comment by fafhrd91** [comment]
I am not sure letsencrypt support should be part of actix-web package. but I can create separate repo in actix org. would you contribute letsencrypt support?

**Comment by cih-y2k** [comment]
I love both the language and the run-time of rust and want we have a mature enough rust web framework with driver supports (database, streaming, etc) and even database systems built with Rust. So I love being able to do some things. But I don't promise because I'm doing a startup with go language, so I'm afraid do not have time yet, at least in near term.

**Comment by fafhrd91** [comment]
closing this as this is relatively low priority. please reopen if anyone decides to contribute

**Comment by ctm** [comment]
In order to support https on my vanity site, I took created [actix-web-lets-encrypt](https://github.com/ctm/actix-web-lets-encrypt). However, I'm new to Rust and spent a bunch of time trying to come up with a nice API and am not happy with what I currently have, although it does indeed give me certificates that work with https (and http/2, although there's nothing http/2 specific in it).

I don't think I can reopen this issue, @fafhrd91 but I'm happy to do more work on this if what I've done is at least somewhat in the right direction.

**Comment by fafhrd91** [comment]
@ctm looks interesting. but you should check actix-web master, it uses actix-net. it would be interesting to build general lets-encrypt integration with actix-net service, then it would be possible to use it with any service not just actix-web
