### ISSUE TITLE
1.0.0 - Can ServiceRequest::from_parts be made public?

### ISSUE THREAD

**Issue by milesgranger** [actix/actix-web#843]
First, thanks for all your hard work, and moving to 1.0 is, for me overall, a good experience. 

I'm writing some middleware which needs access to the `HttpRequest` and the only way I see to accomplish this is `service_request.into_parts()`.

Then to finish the middleware `call` I need to use the `ServiceRequest` for `into_response` or pass to `srv.call(req)`. I was hoping to reconstruct the service request with `ServiceRequest::from_parts` however it turns out it's private. 

Can it be made public, or is there a better way to get `HttpRequest` from this?

**Comment by fafhrd91** [comment]
Why do you need HttpRequest?

**Comment by milesgranger** [comment]
I need to use something like `Query::<HashMap<String, String>>::extract(&request)` to check the query parameters.

**Comment by fafhrd91** [comment]
problem is Clone impl for HttpRequest. while it is part of ServiceRequest we know that it has only one Rc ref. if you build ServiceRequest from parts then it could be cloned multiple time.

i see two options for you, 

ServiceRequest could provide `extract<T: FromRequest>()` method, but in that case result would be `impl Future`, and other option, `Query` extractor could has helper method that work with ServiceRequest instead of HttpRequest

**Comment by milesgranger** [comment]
Thanks for the help. Using `Query` extractor to work with `ServiceRequest` seems like a slick solution. I tried looking a bit, and didn't see where this was possible, so I'm assuming you're talking about a possible implementation yet to be done in actix-web, no?

**Comment by fafhrd91** [comment]
it is not implemented, would you provide PR?

**Comment by milesgranger** [comment]
I'm happy to give it a shot, try to have a WIP in this weekend. 👍
