### ISSUE TITLE
Allow constructing a ServiceRequest from parts

### ISSUE THREAD

**Issue by asonix** [actix/actix-web#861]
I'm trying to implement a middleware to verify Digest headers, which is a header that contains a hash of the request body. In order to check the hash, I need to take the payload from the request, but I'm not extracting any data from the request body itself.

I would like to still be able to use the `Json` or `Form` extractors after I have verified the request digest, but I have no way to put a `Payload` back into a `ServiceRequest`.

This ability could also be useful to implement decompression middleware as well.

**Comment by fafhrd91** [comment]
`from_parts` is not save because HttpRequest clonable, and ServiceRequest assumes that exists only one copy of HttpRequest, and with from_parts you can inject HttpRequest with multiple copies.

but you can take payload via `HttpMessage::take_payload()` and set payload with
`ServiceRequest::set_payload()`

for decompression you have to use https://github.com/actix/actix-web/blob/master/actix-http/src/encoding/decoder.rs#L17
