### ISSUE TITLE
Actix-web unable to use all available CPU resources

### ISSUE THREAD

**Issue by transkatgirl** [actix/actix-web#957]
When attempting to benchmark actix-web, I noticed that no matter how many requests/second I sent to the example code, it would never reach 100% CPU load. 

I used the code from the [basics example](https://github.com/actix/examples/tree/82786d44619e1b79f7a2c3568c54f7388ccca8f4/basics) to text this. The commands I used are listed below.

```
Terminal 1: cargo run --release &> /dev/null
Terminal 2: wrk2 -R 90000 -d 120 http://127.0.0.1:8080
```

Regardless of how many requests/second I threw at actix-web, it refused to use all of the CPU's resources, when run on a 8 core (16 thread) CPU.

![image](https://user-images.githubusercontent.com/10361870/60689938-b4047a80-9e77-11e9-896e-88673b0c8e75.png)

I tested this with the latest available version of actix-web (1.0.3), and the latest versions of the required dependencies. The code was compiled with rustc 1.35.0, and tested on Manjaro Linux (kernel 5.0.21-rt14).

Note that this issue only happens on CPUs with a high core count. Lower end CPUs (such as a 2 core, 4 thread CPU I tested this same code on), do not have this issue.

**Comment by fafhrd91** [comment]
it is hard to tell what is the problem. maybe wrk could no generate enough traffic, or you have io bottleneck. 

Actix in TechEmpower bench could utilize 20 cores

**Comment by transkatgirl** [comment]
Wrk was able to generate enough traffic with previous versions of actix-web. It's unlikely to be an I/O bottleneck, as I'm sending requests to the local device (so no hardware bottlenecking), and I'm requesting the same file over and over (which will result in it being cached by the operating system)

**Comment by Vagelis-Prokopiou** [comment]
@katattakd I had the same problem and it seems that the `workers` config was the cause in my case.
I explain it all in video here: https://youtu.be/gq6pMZ-uYmA
@robjtede I wonder if this configuration should be updated to default to the physical cpus instead of the logical cpus.
Maybe some benchmarking data from multiple people could help determining this issue.

**Comment by robjtede** [comment]
@Vagelis-Prokopiou Thanks for researching this. It might be worth switching the default to physical_cores.

There's another thing worth benchmarking because, in fact, there's another thread running that accepts connections. So if you wanted to match thread -> CPU core 1-to-1 it would have to be `workers = physical_cores - 1`. I suspect there's a trade off in this case where you'd see overall a bit lower latency but with a drop in throughput.

**Comment by Vagelis-Prokopiou** [comment]
@robjtede here is the info:

# Test info
Command: `wrk -t 6 -c 1000 -d 40s url`
Compiler version: `rustc 1.57.0`
System: `Linux debian 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64`
`actix = "0.12"`
`actix-web = "4.0.0-beta.13"`

# 3 runs with `workers(num_cpus::get_physical())`

## Run 1:

```
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    43.40ms    5.26ms 248.79ms   91.45%
    Req/Sec     3.74k   278.21     4.89k    80.33%
  893922 requests in 40.09s, 88.91GB read
Requests/sec:  22298.50
Transfer/sec:      2.22GB
```

## Run 2:

```
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    40.38ms    4.02ms 104.29ms   87.07%
    Req/Sec     4.06k   203.27     4.76k    75.50%
  970307 requests in 40.06s, 96.50GB read
Requests/sec:  24220.60
Transfer/sec:      2.41GB

```

## Run 3:
```
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    38.78ms    3.12ms  89.54ms   90.52%
    Req/Sec     4.23k   239.43     4.81k    73.04%
  1010403 requests in 40.06s, 100.49GB read
Requests/sec:  25224.75
Transfer/sec:      2.51GB
```


# 3 runs with `workers(num_cpus::get_physical() -1)`

## Run 1:
```
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    47.98ms    2.75ms  98.61ms   95.72%
    Req/Sec     3.43k   157.10     3.76k    79.00%
  819757 requests in 40.07s, 81.53GB read
Requests/sec:  20460.23
Transfer/sec:      2.03GB
```

## Run 2:
```
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    47.98ms    2.75ms  98.61ms   95.72%
    Req/Sec     3.43k   157.10     3.76k    79.00%
  819757 requests in 40.07s, 81.53GB read
Requests/sec:  20460.23
Transfer/sec:      2.03GB
```

## Run 3:
```
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    50.44ms    2.84ms 146.01ms   92.21%
    Req/Sec     3.27k   138.98     3.45k    82.17%
  779929 requests in 40.06s, 77.57GB read
Requests/sec:  19469.38
Transfer/sec:      1.94GB
```

It seems that the `workers(num_cpus::get_physical() - 1)` is worse in all tests.
But the point is that the physical number of cpu workers outperforms substantially the logical number of cpu workers.
At least in my case.

**Comment by robjtede** [comment]
Great. Thanks for looking into this.

**Comment by Vagelis-Prokopiou** [comment]
@robjtede a follow up:
It seems that the problem is related to the following concurrency problems, as they are described in Rust for Rustaceans, by Jon Gjengset:
- "Mutual Exclusion"
- "Shared Resource Exhaustion"
- "False Sharing"

More threads (based on virtual CPU cores) do not deterministically lead to better performance.
